=== `credentials`

The `credentials` commands are used to perform credential management operations against Capella clusters.

==== `credentials`

Lists all the credentials on the active cluster:

[options="nowrap"]
```
ðŸ‘¤ Charlie ðŸ  remote
> credentials
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚                  id                  â”‚      name      â”‚ cluster â”‚                                access                                 â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ 354dd662-4d6a-4e1c-80f3-6c78eafa405a â”‚ Administrator  â”‚ remote  â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â”‚ # â”‚    bucket     â”‚         scopes          â”‚     privileges      â”‚ â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤ â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â”‚ 0 â”‚ testing       â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â•®               â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â”‚   â”‚               â”‚ â”‚ 0 â”‚ * â”‚               â”‚ â”‚ 0 â”‚ data_reader â”‚ â”‚ â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â”‚   â”‚               â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â•¯               â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚ â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â”‚ 1 â”‚ travel-sample â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â”‚   â”‚               â”‚ â”‚ 0 â”‚ inventory       â”‚ â”‚ â”‚ 0 â”‚ data_reader â”‚ â”‚ â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â”‚   â”‚               â”‚ â”‚ 1 â”‚ tenant_agent_00 â”‚ â”‚ â”‚ 1 â”‚ data_writer â”‚ â”‚ â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â”‚   â”‚               â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚ â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚
â”‚ 1 â”‚ f0668638-0cf1-417c-8521-abbd1cbf0624 â”‚ Administrator2 â”‚ remote  â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®                      â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â”‚ # â”‚ bucket â”‚  scopes   â”‚     privileges      â”‚                      â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤                      â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â”‚ 0 â”‚ *      â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â•® â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚                      â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â”‚   â”‚        â”‚ â”‚ 0 â”‚ * â”‚ â”‚ â”‚ 0 â”‚ data_reader â”‚ â”‚                      â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â”‚   â”‚        â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â•¯ â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚                      â”‚
â”‚   â”‚                                      â”‚                â”‚         â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯                      â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

In the access section the wild card `*` means that these credentials have access to all those types of resource.
To list the credentials of a cluster other than the active cluster you can use the `--clusters` flag.

==== `credentials create`

Creates credentials using the given username and password against the active Capella cluster.
Note that this command will not work against locally hosted Couchbase Server clusters.

```
ðŸ‘¤ Charlie ðŸ  remote in ðŸ—„ travel-sample._default._default
> credentials create --read --write
Please enter username:
Administrator
Password:
```

Credentials must be created with read and/or write access using the appropriate flags, failure to provide either will result in an error.
When running the command as above you will be prompted to type in the username and password that you want to use.
The Username will be displayed in plaintext, while the Password is hidden for security.

The username and password can also be passed via the appropriate flags:

```
ðŸ‘¤ Charlie ðŸ  remote in ðŸ—„ travel-sample._default._default
> credentials create --username Administrator --password Password1! --read
```

This can be useful if you have a nu script that creates credentials without continuous user interaction.

Finally you can use the `--registered` flag to create credentials using the username and password specified when the cluster was registered with CBShell.
Imagine you have the following entry for a Capella cluster in your https://couchbase.sh/docs/#_the_config_dotfiles[config file]:

```
[[cluster]]
identifier = "remote"
connstr = "couchbases://cb.x78igwqntgo1evov.cloud.couchbase.com"
capella-organization = "my-org"
username = "Administrator"
password = "Password1!"
```

Then you could create credentials using the username and password above as follows:

```
ðŸ‘¤ Charlie ðŸ  remote in ðŸ—„ travel-sample._default._default
> credentials create --read --write --registered
```

This can be useful to avoid entering the username and password multiple times when registering new clusters with the `cb-env register` command as shown https://couchbase.sh/docs/recipes/#_register_clusters[here].
By default the created credentials will have access granted to all buckets/scopes on the active cluster.
If you want to grant access to a specific bucket, this can be done using the bucket flag:

[options="nowrap"]
```
ðŸ‘¤ Charlie ðŸ  remote
> credentials create --read --write --registered --bucket travel-sample
ðŸ‘¤ Charlie ðŸ  remote
> credentials
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚                  id                  â”‚     name      â”‚ cluster â”‚                         access                          â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ 4076108d-88d6-405c-84ab-e8842eec4166 â”‚ Administrator â”‚ remote  â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚ # â”‚    bucket     â”‚  scopes   â”‚     privileges      â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚ 0 â”‚ travel-sample â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â•® â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚   â”‚               â”‚ â”‚ 0 â”‚ * â”‚ â”‚ â”‚ 0 â”‚ data_writer â”‚ â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚   â”‚               â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â•¯ â”‚ â”‚ 1 â”‚ data_reader â”‚ â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚   â”‚               â”‚           â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

And if you want to limit access to specific scopes within that bucket then you can add the scopes flag:

[options="nowrap"]
```
ðŸ‘¤ Charlie ðŸ  remote
> credentials create --read --write --registered --bucket travel-sample --scopes [inventory tenant_agent_00]
ðŸ‘¤ Charlie ðŸ  remote
> credentials
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚                  id                  â”‚     name      â”‚ cluster â”‚                                access                                 â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ fe26b54f-165d-47d6-90ae-2f10ef3c6db1 â”‚ Administrator â”‚ remote  â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚ # â”‚    bucket     â”‚         scopes          â”‚     privileges      â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚ 0 â”‚ travel-sample â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚   â”‚               â”‚ â”‚ 0 â”‚ inventory       â”‚ â”‚ â”‚ 0 â”‚ data_writer â”‚ â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚   â”‚               â”‚ â”‚ 1 â”‚ tenant_agent_00 â”‚ â”‚ â”‚ 1 â”‚ data_reader â”‚ â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚   â”‚               â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Note that to use the scopes flag you must specify a bucket first, else the command will return an error.

==== `credentials drop`

Deletes the credentials with the given ID.
For example if you have the following credentials on the cluster:

```
ðŸ‘¤ Charlie ðŸ  remote
> credentials
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚                  id                  â”‚     name      â”‚ cluster â”‚                      access                      â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ 4df58dbc-0cc7-4aeb-869b-a3f0a154e3dd â”‚ Administrator â”‚ remote  â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚ # â”‚ bucket â”‚  scopes   â”‚     privileges      â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚ 0 â”‚ *      â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â•® â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚   â”‚        â”‚ â”‚ 0 â”‚ * â”‚ â”‚ â”‚ 0 â”‚ data_writer â”‚ â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚   â”‚        â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â•¯ â”‚ â”‚ 1 â”‚ data_reader â”‚ â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â”‚   â”‚        â”‚           â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚ â”‚
â”‚   â”‚                                      â”‚               â”‚         â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Then you can delete using the `id` like this:

```
ðŸ‘¤ Charlie ðŸ  remote
> credentials drop 4df58dbc-0cc7-4aeb-869b-a3f0a154e3dd
ðŸ‘¤ Charlie ðŸ  remote
> credentials
â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ empty list â”‚
â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Like most other commands you can use the `--clusters` flag to run the command against clusters other than the active cluster.
However only one cluster can be specified at a time since credentials only exist on one cluster.