=== `credentials create`

Creates credentials using the given username and password against the active Capella cluster.
Note that this command will not work against locally hosted Couchbase Server clusters.

```
ðŸ‘¤ Charlie ðŸ  remote in ðŸ—„ travel-sample._default._default
> credentials create --read --write
Please enter username:
Administrator
Password:
```

Credentials must be created with read and/or write access using the appropriate flags, failure to provide either will result in an error.
When running the command as above you will be prompted to type in the username and password that you want to use.
The Username will be displayed in plaintext, while the Password is hidden for security.

The username and password can also be passed via the appropriate flags:

```
ðŸ‘¤ Charlie ðŸ  remote in ðŸ—„ travel-sample._default._default
> credentials create --username Administrator --password Password1! --read
```

This can be useful if you have a nu script that creates credentials without continuous user interaction.

Finally you can use the `--registered` flag to create credentials using the username and password specified when the cluster was registered with CBShell.
Imagine you have the following entry for a Capella cluster in your https://couchbase.sh/docs/#_the_config_dotfiles[config file]:

```
[[cluster]]
identifier = "remote"
connstr = "couchbases://cb.x78igwqntgo1evov.cloud.couchbase.com"
capella-organization = "my-org"
username = "Administrator"
password = "Password1!"
```

Then you could create credentials using the username and password above as follows:

```
ðŸ‘¤ Charlie ðŸ  remote in ðŸ—„ travel-sample._default._default
> credentials create --read --write --registered
```

This can be useful to avoid entering the username and password multiple times when registering new clusters with the `cb-env register` command as shown https://couchbase.sh/docs/recipes/#_register_clusters[here].
