=== vector

The vector commands make it easy to explore the value that vector search can add to your data.
Check the recipes for how the vector commands can be combined to implement https://couchbase.sh/docs/recipes.html#_similarity_search[similarity search] or https://couchbase.sh/docs/recipes.html#_simple_rag[simple RAG].

==== `vector search`

Performs a vector search against a named vector index.
Requires a vector to be used as the source of the search which can be supplied in a couple of formats.

For example imagine we have the following document stored in our cluster:

[options="nowrap"]
```
> doc get landmark_10019
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â•®
â”‚ # â”‚       id       â”‚                                                                                                      content                                                                                                      â”‚ ... â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ landmark_10019 â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ ... â”‚
â”‚   â”‚                â”‚ â”‚ title         â”‚ Gillingham (Kent)                                                                                                                                                                             â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ name          â”‚ Royal Engineers Museum                                                                                                                                                                        â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ alt           â”‚                                                                                                                                                                                               â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ address       â”‚ Prince Arthur Road, ME4 4UG                                                                                                                                                                   â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ directions    â”‚                                                                                                                                                                                               â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ phone         â”‚ +44 1634 822839                                                                                                                                                                               â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ tollfree      â”‚                                                                                                                                                                                               â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ email         â”‚                                                                                                                                                                                               â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ url           â”‚ http://www.remuseum.org.uk                                                                                                                                                                    â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ hours         â”‚ Tues - Fri 9.00am to 5.00pm, Sat - Sun 11.30am - 5.00pm                                                                                                                                       â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ image         â”‚                                                                                                                                                                                               â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ price         â”‚                                                                                                                                                                                               â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ content       â”‚ Adult - Â£6.99 for an Adult ticket that allows you to come back for further visits within a year (children's and concessionary tickets also available). Museum on military engineering and the â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚               â”‚  history of the British Empire. A quite extensive collection that takes about half a day to see. Of most interest to fans of British and military history or civil engineering. The outside   â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ collection of tank mounted bridges etc can be seen for free. There is also an extensive series of themed special event weekends, admission to which is included in the cost of the annual     â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ ticket.                                                                                                                                                                                       â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®                                                                                                                                                             â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ geo           â”‚ â”‚ lat      â”‚ 51.39              â”‚                                                                                                                                                             â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â”‚ lon      â”‚ 0.54               â”‚                                                                                                                                                             â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â”‚ accuracy â”‚ RANGE_INTERPOLATED â”‚                                                                                                                                                             â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯                                                                                                                                                             â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ activity      â”‚ see                                                                                                                                                                                           â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ type          â”‚ landmark                                                                                                                                                                                      â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ id            â”‚ 10019                                                                                                                                                                                         â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ country       â”‚ United Kingdom                                                                                                                                                                                â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ city          â”‚ Gillingham                                                                                                                                                                                    â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ state         â”‚                                                                                                                                                                                               â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â•­â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â•®                                                                                                                                                                              â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ contentVector â”‚ â”‚    0 â”‚  0.02 â”‚                                                                                                                                                                              â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â”‚  ... â”‚   ... â”‚                                                                                                                                                                              â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â”‚ 1023 â”‚ -0.00 â”‚                                                                                                                                                                              â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â•°â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â•¯                                                                                                                                                                              â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚     â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â•¯
```

The field `contentVector` contains a vector of dimension 1024 that could be used as the input to a vector search.
Due to the format of the data returned by  https://couchbase.sh/docs/#_doc_get[doc get] we need to https://www.nushell.sh/commands/docs/flatten.html[flatten] to remove the nesting then https://www.nushell.sh/commands/docs/select.html[select] the `contentVector` field:

```
> doc get landmark_10019 | flatten | select contentVector
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚  contentVector   â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ â•­â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â•® â”‚
â”‚   â”‚ â”‚    0 â”‚  0.03 â”‚ â”‚
â”‚   â”‚ â”‚ ...  â”‚  ...  â”‚ â”‚
â”‚   â”‚ â”‚ 1023 â”‚ -0.00 â”‚ â”‚
â”‚   â”‚ â•°â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

This can then be piped directly into `vector search`:

[options="nowrap"]
```
> doc get landmark_10019 | flatten | select contentVector | vector search landmark-content-index contentVector
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚       id       â”‚                  score                  â”‚ cluster â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ landmark_10019 â”‚ 340282350000000000000000000000000000000 â”‚ local   â”‚
â”‚ 1 â”‚ landmark_28965 â”‚ 1.0286634                               â”‚ local   â”‚
â”‚ 2 â”‚ landmark_3547  â”‚ 1.0150017                               â”‚ local   â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

We specify the vector index to be queried (landmark-content-index) as well as the name of the field on which the vector index was created (contentVector).
See <<_vector_create_index,vector create-index>> for further explanation.

<<_subdoc_get, Subdoc get>> can also be used to fetch the source vector:

[options="nowrap"]
```
> subdoc get contentVector landmark_10019 | select content | vector search landmark-content-index contentVector
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚       id       â”‚                  score                  â”‚ cluster â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ landmark_10019 â”‚ 340282350000000000000000000000000000000 â”‚ local   â”‚
â”‚ 1 â”‚ landmark_28965 â”‚ 1.0286634                               â”‚ local   â”‚
â”‚ 2 â”‚ landmark_3547  â”‚ 1.0150017                               â”‚ local   â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Here we don't need to flatten and specify the field since the content of the `sub doc` output already only holds the `contentVector` field.

Another format that is accepted is the output of  <<_vector_enrich_text,vector enrich-text>> :

```
> vector enrich-text "some string" --dimension 1024 | vector search landmark-content-index contentVector
Embedding batch 1/1
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚       id       â”‚   score    â”‚ cluster â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ landmark_21681 â”‚ 0.70561004 â”‚ local   â”‚
â”‚ 1 â”‚ landmark_20732 â”‚ 0.7003826  â”‚ local   â”‚
â”‚ 2 â”‚ landmark_21682 â”‚ 0.6987926  â”‚ local   â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Note the `--dimension` flag used here, the vector provided as the source of the search must match the dimension of the vectors on which the index was <<_vector_create_index,created>> else you will get no results.

Finally if you just have a plain vector that is a list of floats this can be passed in as a final positional parameter:

```
> let vector = [0.1 0.2 0.3 0.4]
> vector search vector-index fieldName $vector
```

The vector here only has a dimension of 4 which is unrealistically low, but it is used for illustrative purposes.

The output of the search is a table containing the IDs of the `n` (specified by the `--neighbours` flag) documents with the most similar vector in the field named.
The similarity of vectors is calculated using the metric specified on <<_vector_create_index,index creation>>.

To see the contents of the documents identified in the table simply pipe the output of vector search into a https://couchbase.sh/docs/#_doc_get[doc get] command.
If only interested in a particular field then the <<_subdoc_get,subdoc get>> command will also work in the same way:

```
ðŸ‘¤ Charlie ðŸ  local in â˜ï¸ default._default._default
> vector search landmark-content-index contentVector $vector | subdoc get address
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚       id       â”‚                content                â”‚         cas         â”‚ error â”‚ cluster â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ landmark_11956 â”‚ Hornchurch Road, Hornchurch, RM11 1JU â”‚ 1722871671832641536 â”‚       â”‚ local   â”‚
â”‚ 1 â”‚ landmark_25284 â”‚ 4040 Twiggs St                        â”‚ 1722871685304025088 â”‚       â”‚ local   â”‚
â”‚ 2 â”‚ landmark_7744  â”‚ Grandstand Road                       â”‚ 1722871709487202304 â”‚       â”‚ local   â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

The environment is important when using the `vector search` command as the fully qualified index name is constructed from the active bucket and scope.
The above command will be trying to use the index `default._default.landmark-content-index`.
If the index was created against a different bucket/scope then you will get an index not found error.

[options="nowrap"]
```
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample.inventory._default
> vector search landmark-content-index contentVector $vector
Error:   Ã— Unexpected status code
   â•­â”€[entry #4:1:1]
 1 â”‚ vector search landmark-content-index contentVector $vector
   Â· â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€
   Â·       â•°â”€â”€
   â•°â”€â”€â”€â”€
  help: Unexpected status code: 400, body: {"error":"rest_auth: preparePerms, err: index not found","request":{"ctl":{"timeout":75000},"knn":[{"field":"contentVector","k":3,"vector":
  ...
```

If you want to use an index that was created against a different bucket/scope to those that are active, this can be done with the `--bucket` and `--scope` flags.

```
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample.inventory._default
> vector search landmark-content-index contentVector $vector --bucket default --scope _default
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚       id       â”‚                  score                  â”‚ cluster â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ landmark_10019 â”‚ 340282350000000000000000000000000000000 â”‚ local   â”‚
â”‚ 1 â”‚ landmark_16379 â”‚ 1.0082568                               â”‚ local   â”‚
â”‚ 2 â”‚ landmark_33857 â”‚ 0.9897698                               â”‚ local   â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

==== `vector create-index`

Creates a vector index against the active bucket/scope or the bucket/scope specified with the corresponding flags.
For example the following will create an index named new-vector-index over the field fieldName in documents in the bucket `default` and the scope `_default`:

```
ðŸ‘¤ Charlie ðŸ  local in â˜ï¸ default._default._default
> vector create-index new-vector-index fieldName 1024
```

Any documents located elsewhere will not be indexed, and a vector search performed with this index will not find them.
If the documents to be indexed were stored elsewhere then the environment would need to be changed with `cb-env bucket/scope` or the bucket and scope could be passed in with the appropriate flags.

The field parameter is the name of the field in the documents that contains the vector, and the dimension (length of the vector) parameter must match that of the vectors contained in the named field.
Imagine there are documents with the following structure in the bucket `users` and scope `embeddedUsers`:

```
{
    "name": "my-name",
    "e-mail": "shell-user@couchbase.com",
    "description": "A rich textual description of the user.",
    "descriptionEmbedding": [0.0178287, 0.123098, -0.0189239, 1.109238],
}
```

In this example the descriptionEmbedding is the result of using a large language model to generate an embedding from the description field.
The dimension of the vector (4) is unrealistically low but it's been chosen for illustrative purposes.
To create an index over such documents in order to find users with similar descriptions the command would be:

```
ðŸ‘¤ Charlie ðŸ  local in â˜ï¸ users.embeddedUsers._default
> vector create-index user-description-index descriptionEmbedding 4

or

ðŸ‘¤ Charlie ðŸ  local in â˜ï¸ default._default._default
> vector create-index user-description-index descriptionEmbedding 4 --bucket users --scope embeddedUsers
```

In the first example the create command is run from within the bucket and scope that the documents are stored in.
Whereas in the latter the environment values need to be overwritten with the `--bucket` and `--scope` flags to correctly create the index.

==== `vector enrich-doc`

Enriches an existing json document by generating an embedding using the <<_cb_env_llm,active llm>> from a named field and storing it in a new field in the same document.

For example take one of the documents from the travel sample data set:

[options="nowrap"]
```
> doc get landmark_10019
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â•®
â”‚ # â”‚       id       â”‚                                                                                                        content                                                                                                         â”‚ ... â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ landmark_10019 â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ ... â”‚
â”‚   â”‚                â”‚ â”‚ title      â”‚ Gillingham (Kent)                                                                                                                                                                                     â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ name       â”‚ Royal Engineers Museum                                                                                                                                                                                â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ alt        â”‚                                                                                                                                                                                                       â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ address    â”‚ Prince Arthur Road, ME4 4UG                                                                                                                                                                           â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ directions â”‚                                                                                                                                                                                                       â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ phone      â”‚ +44 1634 822839                                                                                                                                                                                       â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ tollfree   â”‚                                                                                                                                                                                                       â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ email      â”‚                                                                                                                                                                                                       â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ url        â”‚ http://www.remuseum.org.uk                                                                                                                                                                            â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ hours      â”‚ Tues - Fri 9.00am to 5.00pm, Sat - Sun 11.30am - 5.00pm                                                                                                                                               â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ image      â”‚                                                                                                                                                                                                       â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ price      â”‚                                                                                                                                                                                                       â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ content    â”‚ Adult - Â£6.99 for an Adult ticket that allows you to come back for further visits within a year (children's and concessionary tickets also available). Museum on military engineering and the history â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚            â”‚  of the British Empire. A quite extensive collection that takes about half a day to see. Of most interest to fans of British and military history or civil engineering. The outside collection of     â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚            â”‚ tank mounted bridges etc can be seen for free. There is also an extensive series of themed special event weekends, admission to which is included in the cost of the annual ticket.                   â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚            â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®                                                                                                                                                                     â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ geo        â”‚ â”‚ lat      â”‚ 51.39              â”‚                                                                                                                                                                     â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚            â”‚ â”‚ lon      â”‚ 0.54               â”‚                                                                                                                                                                     â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚            â”‚ â”‚ accuracy â”‚ RANGE_INTERPOLATED â”‚                                                                                                                                                                     â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚            â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯                                                                                                                                                                     â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ activity   â”‚ see                                                                                                                                                                                                   â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ type       â”‚ landmark                                                                                                                                                                                              â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ id         â”‚ 10019                                                                                                                                                                                                 â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ country    â”‚ United Kingdom                                                                                                                                                                                        â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ city       â”‚ Gillingham                                                                                                                                                                                            â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â”‚ state      â”‚                                                                                                                                                                                                       â”‚ â”‚     â”‚
â”‚   â”‚                â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚     â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â•¯
```

We can use the content field to generate an embedding, and the result will be a new document that is the same as the original, with a new field containing the vector that is the result of the embedding generation:

[options="nowrap"]
```
> doc get landmark_10019 | vector enrich-doc content
Embedding batch 1/1
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚       id       â”‚                                                                                                         content                                                                                                         â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ landmark_10019 â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚
â”‚   â”‚                â”‚ â”‚ title         â”‚ Gillingham (Kent)                                                                                                                                                                                   â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ name          â”‚ Royal Engineers Museum                                                                                                                                                                              â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ alt           â”‚                                                                                                                                                                                                     â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ address       â”‚ Prince Arthur Road, ME4 4UG                                                                                                                                                                         â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ directions    â”‚                                                                                                                                                                                                     â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ phone         â”‚ +44 1634 822839                                                                                                                                                                                     â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ tollfree      â”‚                                                                                                                                                                                                     â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ email         â”‚                                                                                                                                                                                                     â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ url           â”‚ http://www.remuseum.org.uk                                                                                                                                                                          â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ hours         â”‚ Tues - Fri 9.00am to 5.00pm, Sat - Sun 11.30am - 5.00pm                                                                                                                                             â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ image         â”‚                                                                                                                                                                                                     â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ price         â”‚                                                                                                                                                                                                     â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ content       â”‚ Adult - Â£6.99 for an Adult ticket that allows you to come back for further visits within a year (children's and concessionary tickets also available). Museum on military engineering and the       â”‚ â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ history of the British Empire. A quite extensive collection that takes about half a day to see. Of most interest to fans of British and military history or civil engineering. The outside          â”‚ â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ collection of tank mounted bridges etc can be seen for free. There is also an extensive series of themed special event weekends, admission to which is included in the cost of the annual ticket.   â”‚ â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®                                                                                                                                                                   â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ geo           â”‚ â”‚ lat      â”‚ 51.39              â”‚                                                                                                                                                                   â”‚ â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â”‚ lon      â”‚ 0.54               â”‚                                                                                                                                                                   â”‚ â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â”‚ accuracy â”‚ RANGE_INTERPOLATED â”‚                                                                                                                                                                   â”‚ â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯                                                                                                                                                                   â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ activity      â”‚ see                                                                                                                                                                                                 â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ type          â”‚ landmark                                                                                                                                                                                            â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ id            â”‚ 10019                                                                                                                                                                                               â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ country       â”‚ United Kingdom                                                                                                                                                                                      â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ city          â”‚ Gillingham                                                                                                                                                                                          â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ state         â”‚                                                                                                                                                                                                     â”‚ â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â•­â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â•®                                                                                                                                                                                    â”‚ â”‚
â”‚   â”‚                â”‚ â”‚ contentVector â”‚ â”‚    0 â”‚  0.02 â”‚                                                                                                                                                                                    â”‚ â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â”‚  ... â”‚   ... â”‚                                                                                                                                                                                    â”‚ â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â”‚ 1535 â”‚ -0.01 â”‚                                                                                                                                                                                    â”‚ â”‚
â”‚   â”‚                â”‚ â”‚               â”‚ â•°â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â•¯                                                                                                                                                                                    â”‚ â”‚
â”‚   â”‚                â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

The resulting document is the same as the original, but with a new field `contentVector` which contains the result of embedding the content field with the <<_cb_env_llm,active llm>>.
The name of the field that the embedding will be written to will default to the name of the original field with "Vector" appended.
This default behavior can be overwritten with the `vectorField` flag.
The resulting document is formatted with an id and content column which allows it to be piped into a `doc upsert` command to store it in the connected couchbase cluster.

```
> doc get landmark_10019 | vector enrich-doc content | doc upsert
Embedding batch 1/1
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ processed â”‚ success â”‚ failed â”‚ failures â”‚ cluster â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚         1 â”‚       1 â”‚      0 â”‚          â”‚ local   â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

`vector enrich-doc` can enrich more than one document at a time.
To repeat what we have done above on all the landmark documents we can get all the docs using a query and pipe the result directly into the `enrich-doc` command:

```
> query "SELECT meta().id, * FROM `travel-sample` WHERE type = 'landmark'" | vector enrich-doc content
```

When using the result of a query as the input to `enrich-doc` you need to query for the document id as well as the contents, hence "SELECT meta().id, *".
This allows the new document output by the command to have the same id as the original.
If there is another field in the doc that you want to use as the id in the resulting documents then just select this and specify the field with the `--id-column` flag.
For example to use the "name" field as the id of the resulting documents do:

[options="nowrap"]
```
> query "SELECT name, * FROM `travel-sample` WHERE type = 'landmark'" | vector enrich-doc content --id-column name
```

==== `vector enrich-text`

Generates an embedding from the input text using the <<_cb_env_llm,active_llm>> and outputs a json document containing the source text and the embedding.

It can be used directly on strings, which can be passed in as a positional parameter:

```
> vector enrich-text "some string" --dimension 5
Embedding batch 1/1
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚      id       â”‚          content           â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ vector-c9e02c â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚
â”‚   â”‚               â”‚ â”‚ text   â”‚ some string   â”‚ â”‚
â”‚   â”‚               â”‚ â”‚        â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â•® â”‚ â”‚
â”‚   â”‚               â”‚ â”‚ vector â”‚ â”‚ 0 â”‚  0.31 â”‚ â”‚ â”‚
â”‚   â”‚               â”‚ â”‚        â”‚ â”‚ 1 â”‚ -0.61 â”‚ â”‚ â”‚
â”‚   â”‚               â”‚ â”‚        â”‚ â”‚ 2 â”‚ -0.21 â”‚ â”‚ â”‚
â”‚   â”‚               â”‚ â”‚        â”‚ â”‚ 3 â”‚ -0.59 â”‚ â”‚ â”‚
â”‚   â”‚               â”‚ â”‚        â”‚ â”‚ 4 â”‚ -0.38 â”‚ â”‚ â”‚
â”‚   â”‚               â”‚ â”‚        â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚ â”‚
â”‚   â”‚               â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Or piped directly in:

```
> "some string" | vector enrich-text --dimension 5
Embedding batch 1/1
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚      id       â”‚          content           â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ vector-a269a7 â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚
â”‚   â”‚               â”‚ â”‚ text   â”‚ some string   â”‚ â”‚
â”‚   â”‚               â”‚ â”‚        â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â•® â”‚ â”‚
â”‚   â”‚               â”‚ â”‚ vector â”‚ â”‚ 0 â”‚  0.31 â”‚ â”‚ â”‚
â”‚   â”‚               â”‚ â”‚        â”‚ â”‚ 1 â”‚ -0.61 â”‚ â”‚ â”‚
â”‚   â”‚               â”‚ â”‚        â”‚ â”‚ 2 â”‚ -0.21 â”‚ â”‚ â”‚
â”‚   â”‚               â”‚ â”‚        â”‚ â”‚ 3 â”‚ -0.59 â”‚ â”‚ â”‚
â”‚   â”‚               â”‚ â”‚        â”‚ â”‚ 4 â”‚ -0.38 â”‚ â”‚ â”‚
â”‚   â”‚               â”‚ â”‚        â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚ â”‚
â”‚   â”‚               â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Note that the dimension used here (5) is unrealistically low, but has just been chosen for illustrative purposes.

The output is in a format that means it can be piped directly into a `doc upsert` command to upsert it into the cluster:

```
> "some string" | vector enrich-text --dimension 5 | doc upsert
Embedding batch 1/1
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ processed â”‚ success â”‚ failed â”‚ failures â”‚ cluster â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚         1 â”‚       1 â”‚      0 â”‚          â”‚ local   â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Or the output can be piped directly into `vector search` to find indexed docs with a similar vector.
This makes `vector enrich-text` a very easy way to experiment with similarity search using strings.
See <<_vector_search,vector search>> for an example of this.

`vector enrich-text` can also be used on larger chunks of text to produce multiple `vector docs` at once.
For example say you have a text file called `some-text.txt`:

```
> open some-text.txt | vector enrich-text | doc upsert
Embedding batch 1/1
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ processed â”‚ success â”‚ failed â”‚ failures â”‚ cluster â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚        92 â”‚      92 â”‚      0 â”‚          â”‚ local   â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

When used on larger amounts of text `vector enrich-text` will split it into chunks of length 1024 by default, the length of the chunks can be changed with the `--chunks` flag.
In this example the contents of `some-text.txt` was split into 92 chunks, resulting in 92 `vector docs` that were then upserted into the connected cluster.

Finally if you have a set of files within a directory that you want to generate `vector docs` from then you can list the files in the current directory with `ls` and pipe this list into `vector enrich-text`:

```
> ls | vector enrich-text | doc upsert
Embedding batch 1/1
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ processed â”‚ success â”‚ failed â”‚ failures â”‚ cluster â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚       278 â”‚     278 â”‚      0 â”‚          â”‚ local   â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Here `vector enrich-text` will read each file, chunk the contents, retrieve the embeddings then generate the `vector docs`.
Check this https://couchbase.sh/docs/recipes.html#_simple_rag[recipe] to see how `vector enrich-text` enables the implementation of simple Retrieval Augmented Generation. 