== Exporting data

Couchbase Shell supports exporting data to a variety of formats and sources.
These recipes will cover exporting data through different Couchbase services to be stored in a variety of formats.

=== From key-value

The simplest way to get a document from the connected cluster is using the https://couchbase.sh/docs/#_doc_get[doc get] command.

```
> doc get airport_3719 --bucket travel-sample
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚      id      â”‚              content               â”‚         cas         â”‚ error â”‚ cluster â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ airport_3719 â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ 1712321632867319808 â”‚       â”‚ local   â”‚
â”‚   â”‚              â”‚ â”‚ id          â”‚ 3719             â”‚ â”‚                     â”‚       â”‚         â”‚
â”‚   â”‚              â”‚ â”‚ type        â”‚ airport          â”‚ â”‚                     â”‚       â”‚         â”‚
â”‚   â”‚              â”‚ â”‚ airportname â”‚ Columbia Rgnl    â”‚ â”‚                     â”‚       â”‚         â”‚
â”‚   â”‚              â”‚ â”‚ city        â”‚ Columbia         â”‚ â”‚                     â”‚       â”‚         â”‚
â”‚   â”‚              â”‚ â”‚ country     â”‚ United States    â”‚ â”‚                     â”‚       â”‚         â”‚
â”‚   â”‚              â”‚ â”‚ faa         â”‚ COU              â”‚ â”‚                     â”‚       â”‚         â”‚
â”‚   â”‚              â”‚ â”‚ icao        â”‚ KCOU             â”‚ â”‚                     â”‚       â”‚         â”‚
â”‚   â”‚              â”‚ â”‚ tz          â”‚ America/Chicago  â”‚ â”‚                     â”‚       â”‚         â”‚
â”‚   â”‚              â”‚ â”‚             â”‚ â•­â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ â”‚                     â”‚       â”‚         â”‚
â”‚   â”‚              â”‚ â”‚ geo         â”‚ â”‚ lat â”‚ 38.82  â”‚ â”‚ â”‚                     â”‚       â”‚         â”‚
â”‚   â”‚              â”‚ â”‚             â”‚ â”‚ lon â”‚ -92.22 â”‚ â”‚ â”‚                     â”‚       â”‚         â”‚
â”‚   â”‚              â”‚ â”‚             â”‚ â”‚ alt â”‚ 889.00 â”‚ â”‚ â”‚                     â”‚       â”‚         â”‚
â”‚   â”‚              â”‚ â”‚             â”‚ â•°â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚ â”‚                     â”‚       â”‚         â”‚
â”‚   â”‚              â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚                     â”‚       â”‚         â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

The `doc get` command exposes data as three fields; `id`, `cas`, and `content`, where the body of the document is stored within the `content` column.
If you want to only store the document body then you can use `doc get <id> | get content`, then pipe this to Nushell's https://www.nushell.sh/commands/docs/save.html[save] command.

```
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> doc get airport_3719 | get content | save mydoc.json
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> cat mydoc.json
[
  {
    "id": 3719,
    "type": "airport",
    "airportname": "Columbia Rgnl",
    "city": "Columbia",
    "country": "United States",
    "faa": "COU",
    "icao": "KCOU",
    "tz": "America/Chicago",
    "geo":
    {
      "lat": 38.818094,
      "lon": -92.219631,
      "alt": 889
    }
  }
]
```

When using Nushell's https://www.nushell.sh/commands/docs/get.html[get] we can specify either a column from the input table or a specific cell path.
Since we have just specified a column name we are piping a list of length 1 into `save` and `mydoc.json` contains an array of our single JSON object.
If we want to store the body as a single JSON object, we can `get` the first item from the `content` column with `get content.0`.

```
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> doc get airport_3719 | get content.0 | save mydoc.json -f
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> cat mydoc.json
{
  "id": 3719,
  "type": "airport",
  "airportname": "Columbia Rgnl",
  "city": "Columbia",
  "country": "United States",
  "faa": "COU",
  "icao": "KCOU",
  "tz": "America/Chicago",
  "geo":
  {
    "lat": 38.818094,
    "lon": -92.219631,
    "alt": 889
  }
}
```

Here we use `-f` with the `save` command to overwrite the `mydoc.json` created in the previous example.
In these examples we have saved the data as JSON, the same format as it is stored in the cluster.
However CBShell can be used to transform the format of data for example we may want to save the same document but this time in CSV.

Let's use the same document as in the last example:

[options="nowrap"]
```
> doc get airport_3719 --bucket travel-sample | get content
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚  id  â”‚  type   â”‚  airportname  â”‚   city   â”‚    country    â”‚ faa â”‚ icao â”‚       tz        â”‚       geo        â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ 3719 â”‚ airport â”‚ Columbia Rgnl â”‚ Columbia â”‚ United States â”‚ COU â”‚ KCOU â”‚ America/Chicago â”‚ â•­â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚
â”‚   â”‚      â”‚         â”‚               â”‚          â”‚               â”‚     â”‚      â”‚                 â”‚ â”‚ lat â”‚ 38.82  â”‚ â”‚
â”‚   â”‚      â”‚         â”‚               â”‚          â”‚               â”‚     â”‚      â”‚                 â”‚ â”‚ lon â”‚ -92.22 â”‚ â”‚
â”‚   â”‚      â”‚         â”‚               â”‚          â”‚               â”‚     â”‚      â”‚                 â”‚ â”‚ alt â”‚ 889.00 â”‚ â”‚
â”‚   â”‚      â”‚         â”‚               â”‚          â”‚               â”‚     â”‚      â”‚                 â”‚ â•°â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

The `geo` column in the above data contains a https://www.nushell.sh/book/working_with_records.html[record], which means that the data is nested.
This means that we have to flatten out the `geo` column due to limitations of the CSV format.
If we try to export the content into CSV as it is then we will see:

```
> doc get airport_3719 --bucket travel-sample | get content | to csv
Error: nu::shell::cant_convert (link)

  Ã— Can't convert to CSV.
   â•­â”€[entry #25:1:1]
 1 â”‚ doc get airport_3719 --bucket travel-sample | get content | to csv
   Â· â”€â”€â”€â”¬â”€â”€â”€
   Â·    â•°â”€â”€ can't convert table<airportname: string, city: string, country: string, faa: string, geo: record<alt: float, lat: float, lon: float>, icao: string, id: int, type: string, tz: string> to CSV
   â•°â”€â”€â”€â”€
```

Fortunately the native Nushell https://www.nushell.sh/commands/docs/flatten.html[flatten] command removes this nesting:

[options="nowrap"]
```
> doc get airport_3719 --bucket travel-sample | get content | flatten
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚  id  â”‚  type   â”‚  airportname  â”‚   city   â”‚    country    â”‚ faa â”‚ icao â”‚       tz        â”‚  lat  â”‚  lon   â”‚  alt   â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ 3719 â”‚ airport â”‚ Columbia Rgnl â”‚ Columbia â”‚ United States â”‚ COU â”‚ KCOU â”‚ America/Chicago â”‚ 38.82 â”‚ -92.22 â”‚ 889.00 â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Once flat we can then pipe to save:

```
> doc get airport_3719 --bucket travel-sample | get content | flatten | save mydoc.csv
> cat mydoc.csv
id,type,airportname,city,country,faa,icao,tz,lat,lon,alt
3719,airport,Columbia Rgnl,Columbia,United States,COU,KCOU,America/Chicago,38.818094,-92.219631,889
```

=== From Query

While the key-value service can be very useful for exporting small numbers of documents based on their IDs, the Query service can be powerful for fetching large numbers of documents.
For example we can https://couchbase.sh/docs/#_query_2[query] for the first 5 documents of type airport:

[options="nowrap"]
```
>  query "SELECT `travel-sample`.* from `travel-sample` WHERE `type`='airport' LIMIT 5"
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚       airportname       â”‚       city        â”‚    country    â”‚ faa â”‚        geo        â”‚ icao â”‚  id  â”‚  type   â”‚         tz          â”‚ cluster â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ Boeing Fld King Co Intl â”‚ Seattle           â”‚ United States â”‚ BFI â”‚ â•­â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ KBFI â”‚ 3726 â”‚ airport â”‚ America/Los_Angeles â”‚ local   â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â”‚ alt â”‚ 21      â”‚ â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â”‚ lat â”‚ 47.53   â”‚ â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â”‚ lon â”‚ -122.30 â”‚ â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â•°â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚ 1 â”‚ Bray                    â”‚ Albert            â”‚ France        â”‚     â”‚        âŽ         â”‚ LFAQ â”‚ 1258 â”‚ airport â”‚ Europe/Paris        â”‚ local   â”‚
â”‚ 2 â”‚ Calais Dunkerque        â”‚ Calais            â”‚ France        â”‚ CQF â”‚        âŽ         â”‚ LFAC â”‚ 1254 â”‚ airport â”‚ Europe/Paris        â”‚ local   â”‚
â”‚ 3 â”‚ Columbia Rgnl           â”‚ Columbia          â”‚ United States â”‚ COU â”‚ â•­â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â•®  â”‚ KCOU â”‚ 3719 â”‚ airport â”‚ America/Chicago     â”‚ local   â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â”‚ alt â”‚ 889    â”‚  â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â”‚ lat â”‚ 38.82  â”‚  â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â”‚ lon â”‚ -92.22 â”‚  â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â•°â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â•¯  â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚ 4 â”‚ Couterne                â”‚ Bagnole-de-l'orne â”‚ France        â”‚     â”‚        âŽ         â”‚ LFAO â”‚ 1257 â”‚ airport â”‚ Europe/Paris        â”‚ local   â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

The simplest way to save these is in a single documents as an array of JSON objects:

```
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> query "SELECT `travel-sample`.* from `travel-sample` WHERE `type`='airport' LIMIT 5" | save airports.json
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> cat airports.json
[
  {
    "airportname": "Boeing Fld King Co Intl",
    "city": "Seattle",
    "country": "United States",
    "faa": "BFI",
    "geo":
    {
      "alt": 21,
      "lat": 47.53,
      "lon": -122.301947
    },
    "icao": "KBFI",
    "id": 3726,
    "type": "airport",
    "tz": "America/Los_Angeles",
    "cluster": "local"
  },
...
  {
    "airportname": "Couterne",
    "city": "Bagnole-de-l'orne",
    "country": "France",
    "faa": "",
    "icao": "LFAO",
    "id": 1257,
    "type": "airport",
    "tz": "Europe/Paris",
    "cluster": "local"
  }
]
```

Alternatively you may want to save the documents separately, as they are stored in the Cluster.
This can be done by iterating over https://www.nushell.sh/commands/docs/each.html[each] of the returned documents and saving them individually:

To Multiple Documents
[options="nowrap"]
```
> query "SELECT `travel-sample`.* FROM `travel-sample` WHERE `type`='airport' LIMIT 5" | each { |it| $it | save (["airport_", $it.id ,".json"] | str join) }
> ls airport*.json
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚       name        â”‚ type â”‚ size  â”‚ modified â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ airport_1254.json â”‚ file â”‚ 197 B â”‚ now      â”‚
â”‚ 1 â”‚ airport_1257.json â”‚ file â”‚ 197 B â”‚ now      â”‚
â”‚ 2 â”‚ airport_1258.json â”‚ file â”‚ 182 B â”‚ now      â”‚
â”‚ 3 â”‚ airport_3719.json â”‚ file â”‚ 284 B â”‚ now      â”‚
â”‚ 4 â”‚ airport_3726.json â”‚ file â”‚ 293 B â”‚ now      â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Here we used Nushell's `each` command to iterate over the returned docs and store them using the `save` command.
The file name that each doc is saved to is constructed by the `(["airport_", $it.id ,".json"] | str join)` clause.
This defines a list of strings: `["airport_", $it.id ,".json"]` which we concatenate using https://www.nushell.sh/commands/docs/str_join.html[str join].
So if the `id` of the document is 1254 the defined list would be `["airport_" 1254 ".json"]` which would yield `airport_1254.json` when concatenated.

Again we may want to store the results of our query in a format other than JSON, so lets look at how we could save the docs as CSV.
Imagine that wee are using the same query to find our source data.

[options="nowrap"]
```
> query "SELECT `travel-sample`.* from `travel-sample` WHERE `type`='airport' LIMIT 5"
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚       airportname       â”‚       city        â”‚    country    â”‚ faa â”‚        geo        â”‚ icao â”‚  id  â”‚  type   â”‚         tz          â”‚ cluster â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ Boeing Fld King Co Intl â”‚ Seattle           â”‚ United States â”‚ BFI â”‚ â•­â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ KBFI â”‚ 3726 â”‚ airport â”‚ America/Los_Angeles â”‚ local   â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â”‚ alt â”‚ 21      â”‚ â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â”‚ lat â”‚ 47.53   â”‚ â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â”‚ lon â”‚ -122.30 â”‚ â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â•°â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚ 1 â”‚ Bray                    â”‚ Albert            â”‚ France        â”‚     â”‚        âŽ         â”‚ LFAQ â”‚ 1258 â”‚ airport â”‚ Europe/Paris        â”‚ local   â”‚
â”‚ 2 â”‚ Calais Dunkerque        â”‚ Calais            â”‚ France        â”‚ CQF â”‚        âŽ         â”‚ LFAC â”‚ 1254 â”‚ airport â”‚ Europe/Paris        â”‚ local   â”‚
â”‚ 3 â”‚ Columbia Rgnl           â”‚ Columbia          â”‚ United States â”‚ COU â”‚ â•­â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â•®  â”‚ KCOU â”‚ 3719 â”‚ airport â”‚ America/Chicago     â”‚ local   â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â”‚ alt â”‚ 889    â”‚  â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â”‚ lat â”‚ 38.82  â”‚  â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â”‚ lon â”‚ -92.22 â”‚  â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚   â”‚                         â”‚                   â”‚               â”‚     â”‚ â•°â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â•¯  â”‚      â”‚      â”‚         â”‚                     â”‚         â”‚
â”‚ 4 â”‚ Couterne                â”‚ Bagnole-de-l'orne â”‚ France        â”‚     â”‚        âŽ         â”‚ LFAO â”‚ 1257 â”‚ airport â”‚ Europe/Paris        â”‚ local   â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Before we save this to CSV all we need to https://www.nushell.sh/commands/docs/flatten.html[flatten] out the nested `geo` field:

```
> query "SELECT `travel-sample`.* from `travel-sample` WHERE `type`='airport' LIMIT 5" | flatten | save mydoc.csv
> cat mydoc.csv
airportname,city,country,faa,alt,lat,lon,icao,id,type,tz,cluster
Boeing Fld King Co Intl,Seattle,United States,BFI,21,47.53,-122.301947,KBFI,3726,airport,America/Los_Angeles,local
Bray,Albert,France,,,,,LFAQ,1258,airport,Europe/Paris,local
Calais Dunkerque,Calais,France,CQF,,,,LFAC,1254,airport,Europe/Paris,local
Columbia Rgnl,Columbia,United States,COU,889,38.818094,-92.219631,KCOU,3719,airport,America/Chicago,local
Couterne,Bagnole-de-l'orne,France,,,,,LFAO,1257,airport,Europe/Paris,local
```
