=== Importing data

Couchbase Shell supports loading data from a variety of formats and sources.

The simplest way to import data is using `doc import` as covered in xref:../intro.adoc[Loading data into the shell].
These recipes will cover more advanced usecases.

==== A Note On Data format

The `doc upsert` command requires there to be only two fields/columns for an upsert.
There can be more than two fields/columns in the data but only two can be used.
By default, these two columns are named `id` and `content`, but these can be overridden with `--id-column` and `--content-column`.

Given the following document format we need to perform some data manipulation to get it into a format which works with `doc upsert`:

```
> cat mydoc.json
{"id":3719,"cas":1600344369374167040,"type":"airport","airportname":"Columbia Rgnl","city":"Columbia","country":"United States","faa":"COU","icao":"KCOU","tz":"America/Chicago"}

> open mydoc.json | wrap content | insert id { |it| echo $it.content.airportname }
╭─────────┬───────────────────╮
│ content │ {record 9 fields} │
│ id      │ Columbia Rgnl     │
╰─────────┴───────────────────╯
```

==== From file

===== From JSON

Single Document
```
> cat mydoc.json
{"id":3719,"cas":1600344369374167040,"type":"airport","airportname":"Columbia Rgnl","city":"Columbia","country":"United States","faa":"COU","icao":"KCOU","tz":"America/Chicago"}

> open mydoc.json | wrap content | insert id { |it|  echo $it.content.airportname } | doc upsert
╭───┬───────────┬─────────┬────────┬──────────┬───────────╮
│ # │ processed │ success │ failed │ failures │  cluster  │
├───┼───────────┼─────────┼────────┼──────────┼───────────┤
│ 0 │         1 │       1 │      0 │          │ dev.local │
╰───┴───────────┴─────────┴────────┴──────────┴───────────╯
```

Multiple Documents
```
> ls airports
───┬────────────────────────────┬──────┬───────┬────────────
 # │            name            │ type │ size  │  modified
───┼────────────────────────────┼──────┼───────┼────────────
 0 │ airports/airport_3719.json │ File │ 151 B │ 2 days ago
 1 │ airports/airport_3720.json │ File │ 155 B │ 2 days ago
 2 │ airports/airport_3721.json │ File │ 172 B │ 2 days ago
 3 │ airports/airport_3722.json │ File │ 161 B │ 2 days ago
 4 │ airports/airport_3723.json │ File │ 163 B │ 2 days ago
 5 │ airports/airport_3724.json │ File │ 156 B │ 2 days ago
 6 │ airports/airport_3725.json │ File │ 148 B │ 2 days ago
 7 │ airports/airport_3726.json │ File │ 164 B │ 2 days ago
 8 │ airports/airport_3727.json │ File │ 169 B │ 2 days ago
 9 │ airports/airport_3728.json │ File │ 152 B │ 2 days ago
───┴────────────────────────────┴──────┴───────┴────────────

> open airports/airport_3719.json
───┬──────┬─────────┬─────────────┬──────────┬─────────┬─────┬──────┬──────────────
 # │  id  │  type   │ airportname │   city   │ country │ faa │ icao │      tz
───┼──────┼─────────┼─────────────┼──────────┼─────────┼─────┼──────┼──────────────
 0 │ 3719 │ airport │ Columbia    │ Columbia │ United  │ COU │ KCOU │ America/Chic
   │      │         │ Rgnl        │          │ States  │     │      │ ago
───┴──────┴─────────┴─────────────┴──────────┴─────────┴─────┴──────┴──────────────

> ls airports/ | each { |it| open $it.name | wrap content | insert id { |doc| echo $doc.content.airportname} } | doc upsert
╭───┬───────────┬─────────┬────────┬──────────┬───────────╮
│ # │ processed │ success │ failed │ failures │  cluster  │
├───┼───────────┼─────────┼────────┼──────────┼───────────┤
│ 0 │        10 │      10 │      0 │          │ dev.local │
╰───┴───────────┴─────────┴────────┴──────────┴───────────╯
```

===== From CSV

Single Document
```
> cat mydoc.csv
id,cas,type,airportname,city,country,faa,icao,tz
3719,1600344369374167040,airport,Columbia Rgnl,Columbia,United States,COU,KCOU,America/Chicago

> open mydoc.csv | each { |it| wrap content | insert id { |doc| echo $doc.content.airportname} } | doc upsert
╭───┬───────────┬─────────┬────────┬──────────┬───────────╮
│ # │ processed │ success │ failed │ failures │  cluster  │
├───┼───────────┼─────────┼────────┼──────────┼───────────┤
│ 0 │         1 │       1 │      0 │          │ dev.local │
╰───┴───────────┴─────────┴────────┴──────────┴───────────╯
```

Multiple Documents
```
> cat airports.csv
airportname,city,country,faa,icao,id,type,tz
Calais Dunkerque,Calais,France,CQF,LFAC,1254,airport,Europe/Paris
Peronne St Quentin,Peronne,France,,LFAG,1255,airport,Europe/Paris
Les Loges,Nangis,France,,LFAI,1256,airport,Europe/Paris
Couterne,Bagnole-de-l'orne,France,,LFAO,1257,airport,Europe/Paris
Bray,Albert,France,,LFAQ,1258,airport,Europe/Paris

>  open mydoc.csv | each { |it| wrap content | insert id { |doc| echo $doc.content.airportname }  } | doc upsert
╭───┬───────────┬─────────┬────────┬──────────┬───────────╮
│ # │ processed │ success │ failed │ failures │  cluster  │
├───┼───────────┼─────────┼────────┼──────────┼───────────┤
│ 0 │        10 │      10 │      0 │          │ dev.local │
╰───┴───────────┴─────────┴────────┴──────────┴───────────╯
```



==== Modifying data

In some circumstances you may want to modify the data before you import it.
Let's take the example of importing from a csv file but this time the airports.csv file is missing the `type` column but we want to add it to our data:
```
> cat airports.csv
airportname,city,country,faa,icao,id,tz
Calais Dunkerque,Calais,France,CQF,LFAC,1254,Europe/Paris
Peronne St Quentin,Peronne,France,,LFAG,1255,Europe/Paris
Les Loges,Nangis,France,,LFAI,1256,Europe/Paris
Couterne,Bagnole-de-l'orne,France,,LFAO,1257,Europe/Paris
Bray,Albert,France,,LFAQ,1258,Europe/Paris

> open airports.csv | insert type airport
╭───┬────────────────────┬───────────────────┬─────────┬─────┬──────┬──────┬──────────────┬─────────╮
│ # │    airportname     │       city        │ country │ faa │ icao │  id  │      tz      │  type   │
├───┼────────────────────┼───────────────────┼─────────┼─────┼──────┼──────┼──────────────┼─────────┤
│ 0 │ Calais Dunkerque   │ Calais            │ France  │ CQF │ LFAC │ 1254 │ Europe/Paris │ airport │
│ 1 │ Peronne St Quentin │ Peronne           │ France  │     │ LFAG │ 1255 │ Europe/Paris │ airport │
│ 2 │ Les Loges          │ Nangis            │ France  │     │ LFAI │ 1256 │ Europe/Paris │ airport │
│ 3 │ Couterne           │ Bagnole-de-l'orne │ France  │     │ LFAO │ 1257 │ Europe/Paris │ airport │
│ 4 │ Bray               │ Albert            │ France  │     │ LFAQ │ 1258 │ Europe/Paris │ airport │
╰───┴────────────────────┴───────────────────┴─────────┴─────┴──────┴──────┴──────────────┴─────────╯
```

We can also add a column based on data from other columns, for instance adding a `type` column which is set to the relevant country:
```
> open airports.csv | each { |it| insert type $it.city }
╭───┬────────────────────┬───────────────────┬─────────┬─────┬──────┬──────┬──────────────┬───────────────────╮
│ # │    airportname     │       city        │ country │ faa │ icao │  id  │      tz      │       type        │
├───┼────────────────────┼───────────────────┼─────────┼─────┼──────┼──────┼──────────────┼───────────────────┤
│ 0 │ Calais Dunkerque   │ Calais            │ France  │ CQF │ LFAC │ 1254 │ Europe/Paris │ Calais            │
│ 1 │ Peronne St Quentin │ Peronne           │ France  │     │ LFAG │ 1255 │ Europe/Paris │ Peronne           │
│ 2 │ Les Loges          │ Nangis            │ France  │     │ LFAI │ 1256 │ Europe/Paris │ Nangis            │
│ 3 │ Couterne           │ Bagnole-de-l'orne │ France  │     │ LFAO │ 1257 │ Europe/Paris │ Bagnole-de-l'orne │
│ 4 │ Bray               │ Albert            │ France  │     │ LFAQ │ 1258 │ Europe/Paris │ Albert            │
╰───┴────────────────────┴───────────────────┴─────────┴─────┴──────┴──────┴──────────────┴───────────────────╯
```
