== Managing multiple clusters

CBShell is a powerful tool that can be used to interact with fleets comprised of a mix of self-managed and Capella clusters.
Say we have the following four clusters registered with CBShell:

```
ðŸ‘¤ Charlie ðŸ  obligingfaronmoller in â˜ï¸ default._default._default
> cb-env managed
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ active â”‚  tls  â”‚ identifier â”‚   username    â”‚ capella_organization â”‚     project     â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ false  â”‚ true  â”‚ systemtest â”‚ Administrator â”‚ my-org               â”‚ CBShell Testing â”‚
â”‚ 1 â”‚ false  â”‚ false â”‚ localdev   â”‚ Administrator â”‚                      â”‚                 â”‚
â”‚ 2 â”‚ false  â”‚ true  â”‚ prod       â”‚ Administrator â”‚ my-org               â”‚ CBShell Testing â”‚
â”‚ 3 â”‚ true   â”‚ true  â”‚ ci         â”‚ Administrator â”‚ my-org               â”‚ CBShell Testing â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

There is one self-managed cluster (localdev) and three Capella clusters.
Imagine that we want to perform some general health checks on this set of clusters, a good starting point is the https://couchbase.sh/docs/#_nodes[nodes] command with the https://couchbase.sh/docs/#_the_clusters_flag[--clusters] flag.

[options="nowrap"]
```
ðŸ‘¤ Charlie ðŸ  localdev in ðŸ—„ travel-sample._default._default
> nodes --clusters *
â•­â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â•®
â”‚  # â”‚         cluster         â”‚                                       hostname              â”‚ status  â”‚         services         â”‚        version        â”‚            os             â”‚ memory_total â”‚ memory_free â”‚ ... â”‚
â”œâ”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¤
â”‚  0 â”‚ localdev                â”‚ 192.168.107.128:8091                                        â”‚ healthy â”‚ search,indexing,kv,query â”‚ 7.6.2-3505-enterprise â”‚ aarch64-unknown-linux-gnu â”‚   6201221120 â”‚  2841657344 â”‚ ... â”‚
â”‚  1 â”‚ localdev                â”‚ 192.168.107.129:8091                                        â”‚ healthy â”‚ search,indexing,kv,query â”‚ 7.6.2-3505-enterprise â”‚ aarch64-unknown-linux-gnu â”‚   6201221120 â”‚  2842959872 â”‚ ... â”‚
â”‚  2 â”‚ localdev                â”‚ 192.168.107.130:8091                                        â”‚ healthy â”‚ search,indexing,kv,query â”‚ 7.6.2-3505-enterprise â”‚ aarch64-unknown-linux-gnu â”‚   6201221120 â”‚  2843160576 â”‚ ... â”‚
â”‚  3 â”‚ prod                    â”‚ svc-dqi-node-001.lhb4l06lajhydwmk.cloud.couchbase.com:8091  â”‚ healthy â”‚ indexing,kv,query        â”‚ 7.6.2-3721-enterprise â”‚ x86_64-pc-linux-gnu       â”‚  16776548352 â”‚ 15518982144 â”‚ ... â”‚
â”‚  4 â”‚ prod                    â”‚ svc-dqi-node-002.lhb4l06lajhydwmk.cloud.couchbase.com:8091  â”‚ healthy â”‚ indexing,kv,query        â”‚ 7.6.2-3721-enterprise â”‚ x86_64-pc-linux-gnu       â”‚  16776548352 â”‚ 15518420992 â”‚ ... â”‚
â”‚  5 â”‚ prod                    â”‚ svc-dqi-node-003.lhb4l06lajhydwmk.cloud.couchbase.com:8091  â”‚ healthy â”‚ indexing,kv,query        â”‚ 7.6.2-3721-enterprise â”‚ x86_64-pc-linux-gnu       â”‚  16776544256 â”‚ 15501099008 â”‚ ... â”‚
â”‚  6 â”‚ ci                      â”‚ svc-dqi-node-001.fwplhqyopu9pgolq.cloud.couchbase.com:8091  â”‚ healthy â”‚ indexing,kv,query        â”‚ 7.6.2-3721-enterprise â”‚ x86_64-pc-linux-gnu       â”‚  16277504000 â”‚ 14538944512 â”‚ ... â”‚
â”‚  7 â”‚ ci                      â”‚ svc-dqi-node-002.fwplhqyopu9pgolq.cloud.couchbase.com:8091  â”‚ healthy â”‚ indexing,kv,query        â”‚ 7.6.2-3721-enterprise â”‚ x86_64-pc-linux-gnu       â”‚  16277504000 â”‚ 14559510528 â”‚ ... â”‚
â”‚  8 â”‚ ci                      â”‚ svc-dqi-node-003.fwplhqyopu9pgolq.cloud.couchbase.com:8091  â”‚ healthy â”‚ indexing,kv,query        â”‚ 7.6.2-3721-enterprise â”‚ x86_64-pc-linux-gnu       â”‚  16277504000 â”‚ 14565412864 â”‚ ... â”‚
â”‚  9 â”‚ systemtest              â”‚ svc-dqi-node-001.lyl8kbhzdovyqhv.cloud.couchbase.com:8091   â”‚ healthy â”‚ indexing,kv,query        â”‚ 7.6.2-3721-enterprise â”‚ x86_64-pc-linux-gnu       â”‚  16766582784 â”‚ 15491842048 â”‚ ... â”‚
â•°â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â•¯
```

This gives us plenty of information, but sometimes it can be a bit difficult to read.
We can make things much easier with some simple reformatting.
To focus on the free memory that each cluster has, we can https://www.nushell.sh/commands/docs/select.html[select] just the relevant columns:

```
ðŸ‘¤ Charlie ðŸ  localdev in ðŸ—„ travel-sample._default._default
> nodes --clusters * | select cluster memory_free
â•­â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚  # â”‚  cluster   â”‚ memory_free â”‚
â”œâ”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚  0 â”‚ localdev   â”‚  2841657344 â”‚
â”‚  1 â”‚ localdev   â”‚  2842959872 â”‚
â”‚  2 â”‚ localdev   â”‚  2843160576 â”‚
â”‚  3 â”‚ prod       â”‚ 15518982144 â”‚
â”‚  4 â”‚ prod       â”‚ 15518420992 â”‚
â”‚  5 â”‚ prod       â”‚ 15501099008 â”‚
â”‚  6 â”‚ ci         â”‚ 14538944512 â”‚
â”‚  7 â”‚ ci         â”‚ 14559510528 â”‚
â”‚  8 â”‚ ci         â”‚ 14565412864 â”‚
â”‚  9 â”‚ systemtest â”‚ 15491842048 â”‚
â•°â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

We can reformat the tables to make the the data more readable, but Nushell's understanding of various data types allows us to reformat the values within the table.
For example we could convert the `memory_free` values from bytes to gigabytes:

[options="nowrap"]
```
ðŸ‘¤ Charlie ðŸ  localdev in ðŸ—„ travel-sample._default._default
> nodes --clusters * | each {|n| $n | update memory_free ($n.memory_free * 1B)} | select cluster memory_free
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚  # â”‚  cluster   â”‚ memory_free â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ localdev    â”‚     2.6 GiB â”‚
â”‚ 1 â”‚ localdev    â”‚     2.6 GiB â”‚
â”‚ 2 â”‚ localdev    â”‚     2.6 GiB â”‚
â”‚ 3 â”‚ prod        â”‚    14.5 GiB â”‚
â”‚ 4 â”‚ prod        â”‚    14.5 GiB â”‚
â”‚ 5 â”‚ prod        â”‚    14.4 GiB â”‚
â”‚ 6 â”‚ ci          â”‚    13.5 GiB â”‚
â”‚ 7 â”‚ ci          â”‚    13.6 GiB â”‚
â”‚ 8 â”‚ ci          â”‚    13.6 GiB â”‚
â”‚ 9 â”‚ systemtest  â”‚    14.4 GiB â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

We do this by iterating over each node and https://www.nushell.sh/commands/docs/update.html[updating] the value in the `memory_free` column by multiplying the current value by Nushell's inbuilt https://www.nushell.sh/book/types_of_data.html#file-sizes[File Size] datatype.

We can take this one step further and use the values returned to calculate new metrics about our clusters.
When performing a health check it's be useful to know the memory utilization for each cluster.
There are two columns that can be used to calculate this: `memory_free` and `memory_total`.

[options="nowrap"]
```
ðŸ‘¤ Charlie ðŸ  localdev in ðŸ—„ travel-sample._default._default
>  nodes --clusters * | each {|n| $n | insert utilization ((($n.memory_total - $n.memory_free) / $n.memory_total) * 100 ) } | select cluster utilization | sort-by utilization --reverse
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚  cluster   â”‚ utilization â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ localdev   â”‚       54.32 â”‚
â”‚ 1 â”‚ localdev   â”‚       54.32 â”‚
â”‚ 2 â”‚ localdev   â”‚       54.28 â”‚
â”‚ 3 â”‚ ci         â”‚       10.71 â”‚
â”‚ 4 â”‚ ci         â”‚       10.60 â”‚
â”‚ 5 â”‚ ci         â”‚       10.50 â”‚
â”‚ 6 â”‚ prod       â”‚        7.61 â”‚
â”‚ 7 â”‚ systemtest â”‚        7.59 â”‚
â”‚ 8 â”‚ prod       â”‚        7.52 â”‚
â”‚ 9 â”‚ prod       â”‚        7.49 â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

For https://www.nushell.sh/commands/docs/each.html[each] of the nodes we add a new column called utilization and we calculate the percentage disk used with:

```
(($n.memory_total - $n.memory_free) / $n.memory_total) * 100
```

Finally we https://www.nushell.sh/commands/docs/sort-by.html[sort-by] descending utilization.

Now that we understand the resources being used by our cluster we can use this information to aid us when deploying a new bucket.
Imagine that we want to create a 1GB bucket on any one of our clusters.
We can use `nodes` to find the cluster with the most free memory and create the bucket there:

[options="nowrap"]
```
ðŸ‘¤ Charlie ðŸ  localdev in ðŸ—„ travel-sample._default._default
> nodes --clusters * | sort-by memory_free --reverse | first | get cluster | buckets create BigBucket 1000 --clusters $in
```

Here we have fetched the nodes for all the registered clusters, sorted by the descending amount of `memory_free` and got the cluster name.
Then we pipe the cluster name into `buckets create` command, using `$in` to access the piped value, and since no error is returned it is a success.
To double check the success and see where our bucket was created we can do:

[options="nowrap"]
```
ðŸ‘¤ Charlie ðŸ  localdev in ðŸ—„ travel-sample._default._default
> buckets --clusters a* | where name == "BigBucket"
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ cluster â”‚   name    â”‚   type    â”‚ replicas â”‚ min_durability_level â”‚ ram_quota  â”‚ flush_enabled â”‚ cloud â”‚ max_expiry â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ prod    â”‚ BigBucket â”‚ couchbase â”‚        1 â”‚ none                 â”‚ 1000.0 MiB â”‚ false         â”‚ true  â”‚          0 â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```



