== Moving data between clusters

CBShell allows data to be moved between clusters, along with buckets, scopes and collections.
Imagine you have 2 clusters, one self-managed (named local) and a Capella cluster called remote:

```
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> cb-env managed
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ active â”‚  tls  â”‚ identifier â”‚   username    â”‚ capella_organization â”‚     project     â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ false  â”‚ true  â”‚ remote     â”‚ Administrator â”‚ my-org               â”‚ CBShell Testing â”‚
â”‚ 1 â”‚ true   â”‚ false â”‚ local      â”‚ Administrator â”‚                      â”‚                 â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

The `remote` cluster is empty while `local` contains two buckets with scopes and collections containing data:

[options="nowrap"]
```
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> buckets
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ cluster â”‚     name      â”‚   type    â”‚ replicas â”‚ min_durability_level â”‚ ram_quota â”‚ flush_enabled â”‚ cloud â”‚ max_expiry â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ local   â”‚ beer-sample   â”‚ couchbase â”‚        1 â”‚ none                 â”‚ 200.0 MiB â”‚ false         â”‚ false â”‚          0 â”‚
â”‚ 1 â”‚ local   â”‚ travel-sample â”‚ couchbase â”‚        1 â”‚ none                 â”‚ 200.0 MiB â”‚ false         â”‚ false â”‚          0 â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

The first thing to do is to recreate all of the buckets that we have on the `local` cluster on the `remote` cluster:

```
> buckets | each {|in| buckets create $in.name ($in.ram_quota / 1MB | into int)  --clusters remote --replicas 1}
```

Here we simply get all of the buckets, then iterate over the list with https://www.nushell.sh/commands/docs/each.html[each] and create buckets with the same name and ram quota, specifying the `remote` cluster with the https://couchbase.sh/docs/#_the_clusters_flag[--clusters] flag.
Since the value for the ram quota is returned in bytes from `buckets` we convert it to MiB by dividing by Nushell's 1MB https://www.nushell.sh/book/types_of_data.html#file-sizes[FileSize] datatype.
We can check that this has worked by running the `buckets` command against the remote cluster:

[options="nowrap"]
```
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> buckets --clusters remote
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ cluster â”‚     name      â”‚   type    â”‚ replicas â”‚ min_durability_level â”‚ ram_quota â”‚ flush_enabled â”‚ cloud â”‚ max_expiry â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ remote  â”‚ beer-sample   â”‚ couchbase â”‚        1 â”‚ none                 â”‚ 209.0 MiB â”‚ false         â”‚ true  â”‚          0 â”‚
â”‚ 1 â”‚ remote  â”‚ travel-sample â”‚ couchbase â”‚        1 â”‚ none                 â”‚ 209.0 MiB â”‚ false         â”‚ true  â”‚          0 â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Next we need to create all of the scopes within these buckets.
First we get all the buckets again on the `local` cluster, then for each of the buckets we get the scopes:

```
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> buckets | each {|bckt| scopes --bucket $bckt.name | where scope not-in [_default _system] | get scope}
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ 0 â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â•®           â”‚
â”‚   â”‚ â”‚ 0 â”‚ Cafes â”‚           â”‚
â”‚   â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â•¯           â”‚
â”‚ 1 â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚
â”‚   â”‚ â”‚ 0 â”‚ inventory       â”‚ â”‚
â”‚   â”‚ â”‚ 1 â”‚ tenant_agent_00 â”‚ â”‚
â”‚   â”‚ â”‚ 2 â”‚ tenant_agent_01 â”‚ â”‚
â”‚   â”‚ â”‚ 3 â”‚ tenant_agent_02 â”‚ â”‚
â”‚   â”‚ â”‚ 4 â”‚ tenant_agent_03 â”‚ â”‚
â”‚   â”‚ â”‚ 5 â”‚ tenant_agent_04 â”‚ â”‚
â”‚   â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Here we iterate over each of the buckets and call `scopes` with the `--bucket` flag to get the scopes from each of them.
Then we use  https://www.nushell.sh/commands/docs/where.html[where] and https://www.nushell.sh/book/operators.html[not-in] operators to filter out the `_default` and `_system` scopes, since these are empty.
Note for the purposes of this demo we have moved the data in beer-sample out of the default scope and collection into the Cafes scope and Breweries collection.

Now that we have listed all the scopes in the buckets, we can amended the previous command to use `scopes create` to create the scopes on the remote cluster:

```
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> buckets | each {|bckt| scopes --bucket $bckt.name | where scope not-in [_default _system] | get scope | each {|scp| scopes create $scp --clusters remote --bucket $bckt.name}}
```

Here we have run the same command to list all the scopes, then for each scope we create one of the same name in the corresponding bucket on the `remote` cluster.

The final step is to do the same with the collections:

```
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> buckets | each {|bckt| scopes --bucket $bckt.name | where scope not-in [_default _system] | get scope | each {|scp| collections --scope $scp --bucket $bckt.name | get collection | each {|col| collections create $col --bucket $bckt.name --scope $scp --clusters remote}}}
```

Here we have fetched the `buckets`, and for each bucket fetched the `scopes` and finally for each of the scopes we have fetched the `collections`.
Then for each of the collections in a bucket/scope we re-create it on the remote cluster in the corresponding buckets/scope.

Before we copy our data over to our new collections we also want to migrate our indexes across.
The first step to doing this is to list all of the index definitions on the `local` cluster as follows:

[options="nowrap"]
```
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> query indexes --definitions | where name != '#primary'
â•­â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â•®
â”‚  # â”‚    bucket     â”‚   scope   â”‚ collection â”‚                 name                  â”‚ status â”‚ storage_mode â”‚ replicas â”‚                                                     definition                                                     â”‚ ... â”‚
â”œâ”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¤
â”‚  0 â”‚ beer-sample   â”‚ _default  â”‚ _default   â”‚ beer_primary                          â”‚ Ready  â”‚ plasma       â”‚        0 â”‚ CREATE PRIMARY INDEX `beer_primary` ON `beer-sample` WITH {  "defer_build":true }                                  â”‚ ... â”‚
â”‚  1 â”‚ travel-sample â”‚ _default  â”‚ _default   â”‚ def_airportname                       â”‚ Ready  â”‚ plasma       â”‚        0 â”‚ CREATE INDEX `def_airportname` ON `travel-sample`(`airportname`) WITH {  "defer_build":true }                      â”‚ ... â”‚
â”‚ .. â”‚      ...      â”‚    ...    â”‚     ...    â”‚                  ...                  â”‚   ...  â”‚      ...     â”‚    ...   â”‚                                                         ...                                                        â”‚ ... â”‚
â”‚ 23 â”‚ travel-sample â”‚ _default  â”‚ _default   â”‚ def_type                              â”‚ Ready  â”‚ plasma       â”‚        0 â”‚ CREATE INDEX `def_type` ON `travel-sample`(`type`) WITH {  "defer_build":true }                                    â”‚ ... â”‚
â•°â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â•¯
```

Here we use https://couchbase.sh/docs/#_query[query] with the definitions flag to fetch all of the query definitions on the active cluster.
Then we have used `where` to filter out all of the primary indexes as these were already created when we created the buckets on the Capella cluster.

Now we can https://www.nushell.sh/commands/docs/select.html[select] the definition column and iterate over the definitions, using `query` to re-create the indexes on the `remote` cluster:

```
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> query indexes --definitions | where name != '#primary' | get definition | each {|def| query $def --clusters remote}
```

The final step is to copy the data from each bucket/scope/collection from the `local` cluster into the corresponding bucket/scope/collection on the `remote` cluster:

```
> buckets | each {|bckt| scopes --bucket $bckt.name | where scope not-in [_default _system] | get scope | each {|scp| collections --scope $scp --bucket $bckt.name | get collection | each {|col| "SELECT meta().id, * FROM `" + $bckt.name + "`." + $scp + "." + $col | query $in | if $in != null {$in | reject cluster | rename id content | doc upsert --bucket $bckt.name --scope $scp --collection $col --clusters remote}}}}
```

Here we have the same nested `each` loops that get the scopes for each bucket then the collections contained within each scope.
We then use the bucket/scope and collection to construct a query:

```
"SELECT meta().id, * FROM `" + $bckt.name + "`." + $scp + "." + $col
```

So when the bucket is `travel-sample` the scope `inventory` and the collection `airline` the above will give:

```
"SELECT meta().id, * FROM `travel-sample`.inventory.airline"
```

We run each of these queries using the `query` command, and pipe the output into the final section of our command:

```
if $in != null {$in | reject cluster | rename id content | doc upsert --bucket $bckt.name --scope $scp --collection $col --clusters remote}
```

To understand what we are doing here you need to know what format the data being output by our queries is in.
If the query run is the example given above then the output will look like this:

```
â•­â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚   # â”‚      id       â”‚                        airline                         â”‚ cluster â”‚
â”œâ”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚   0 â”‚ airline_10    â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®                           â”‚ local   â”‚
â”‚     â”‚               â”‚ â”‚ id       â”‚ 10            â”‚                           â”‚         â”‚
â”‚     â”‚               â”‚ â”‚ type     â”‚ airline       â”‚                           â”‚         â”‚
â”‚     â”‚               â”‚ â”‚ name     â”‚ 40-Mile Air   â”‚                           â”‚         â”‚
â”‚     â”‚               â”‚ â”‚ iata     â”‚ Q5            â”‚                           â”‚         â”‚
â”‚     â”‚               â”‚ â”‚ icao     â”‚ MLA           â”‚                           â”‚         â”‚
â”‚     â”‚               â”‚ â”‚ callsign â”‚ MILE-AIR      â”‚                           â”‚         â”‚
â”‚     â”‚               â”‚ â”‚ country  â”‚ United States â”‚                           â”‚         â”‚
â”‚     â”‚               â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯                           â”‚         â”‚
â”‚ ... â”‚      ...      â”‚                           ...                          â”‚   ...   â”‚
â”‚ 186 â”‚ airline_9833  â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®                           â”‚ local   â”‚
â”‚     â”‚               â”‚ â”‚ id       â”‚ 9833          â”‚                           â”‚         â”‚
â”‚     â”‚               â”‚ â”‚ type     â”‚ airline       â”‚                           â”‚         â”‚
â”‚     â”‚               â”‚ â”‚ name     â”‚ Epic Holiday  â”‚                           â”‚         â”‚
â”‚     â”‚               â”‚ â”‚ iata     â”‚ FA            â”‚                           â”‚         â”‚
â”‚     â”‚               â”‚ â”‚ icao     â”‚ 4AA           â”‚                           â”‚         â”‚
â”‚     â”‚               â”‚ â”‚ callsign â”‚ Epic          â”‚                           â”‚         â”‚
â”‚     â”‚               â”‚ â”‚ country  â”‚ United States â”‚                           â”‚         â”‚
â”‚     â”‚               â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯                           â”‚         â”‚
â•°â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Before we can insert this into our `remote` cluster using https://couchbase.sh/docs/#_doc_upsert[doc upsert] we need it to be correctly https://couchbase.sh/docs/#_manual_import[formatted].
But before we try to reformat any of the data we make sure that the query not returned null with `if $in != null` since trying to manipulate a null value will return an error.
The formatting required is to drop the cluster column which we do using https://www.nushell.sh/commands/docs/reject.html[reject] then rename the column named after the collection, in this case `airline` to `content` which we do using https://www.nushell.sh/commands/docs/rename.html[rename].
After the formatting has been applied to the above example it would become:

```
â•­â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚   # â”‚      id       â”‚                        content                         â”‚
â”œâ”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚   0 â”‚ airline_10    â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®                           â”‚
â”‚     â”‚               â”‚ â”‚ id       â”‚ 10            â”‚                           â”‚
â”‚     â”‚               â”‚ â”‚ type     â”‚ airline       â”‚                           â”‚
â”‚     â”‚               â”‚ â”‚ name     â”‚ 40-Mile Air   â”‚                           â”‚
â”‚     â”‚               â”‚ â”‚ iata     â”‚ Q5            â”‚                           â”‚
â”‚     â”‚               â”‚ â”‚ icao     â”‚ MLA           â”‚                           â”‚
â”‚     â”‚               â”‚ â”‚ callsign â”‚ MILE-AIR      â”‚                           â”‚
â”‚     â”‚               â”‚ â”‚ country  â”‚ United States â”‚                           â”‚
â”‚     â”‚               â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯                           â”‚
â”‚ ... â”‚      ...      â”‚                           ...                          â”‚
â”‚ 186 â”‚ airline_9833  â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®                           â”‚
â”‚     â”‚               â”‚ â”‚ id       â”‚ 9833          â”‚                           â”‚
â”‚     â”‚               â”‚ â”‚ type     â”‚ airline       â”‚                           â”‚
â”‚     â”‚               â”‚ â”‚ name     â”‚ Epic Holiday  â”‚                           â”‚
â”‚     â”‚               â”‚ â”‚ iata     â”‚ FA            â”‚                           â”‚
â”‚     â”‚               â”‚ â”‚ icao     â”‚ 4AA           â”‚                           â”‚
â”‚     â”‚               â”‚ â”‚ callsign â”‚ Epic          â”‚                           â”‚
â”‚     â”‚               â”‚ â”‚ country  â”‚ United States â”‚                           â”‚
â”‚     â”‚               â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯                           â”‚
â•°â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Now that our data is correctly formatted it can be piped into `doc upsert` and using the appropriate flags upserted into the corresponding bucket/scope/collection on our `remote` cluster.




