== Couchbase Capella (DBaaS)

https://cloud.couchbase.com/sign-up?ref=cbsh-web-capella[Couchbase Capella] is a Database as a Service offering from Couchbase which you can interact with from Couchbase Shell.

[#_cb_env_and_the_environment]
=== `cb-env` and the Environment

For general usage of the `cb-env` command see <<cbenv.adoc#_cb_env_and_the_environment>>.
When using <<_management_commands>> with Couchbase Capella and Couchbase Shell we need to be able to manage more active resources than the base `cb-env` command gives us.
You can use the `cb-env --capella` command to see which Capella resources are current active:

```
> cb-env--capella
──────────────────────┬──────────────────
 capella-organization │ mycapellaorg
 project              │ mycapellaproject
──────────────────────┴──────────────────
```

The active resource can be changed with the `cb-env` command:

```
> cb-env -h
Modify the default execution environment of commands

Usage:
  > cb-env <subcommand> {flags}

Subcommands:
  cb-env bucket - Sets the active bucket based on its name
  cb-env capella-organization - Sets the active capella organization based on its identifier
  cb-env cluster - Sets the active cluster based on its identifier
  cb-env collection - Sets the active collection based on its name
  cb-env project - Sets the active project based on its name
  cb-env scope - Sets the active scope based on its name
```

=== Document Level Commands

Document level commands like those under `doc`, `analytics`, `query`, and `search` (with a couple of exceptions) do not require any special changes to the `config` config file.

You need to:

- https://docs.couchbase.com/cloud/clusters/create-cluster.html[create a cluster] in your Couchbase Capella account
- ensure that your https://docs.couchbase.com/cloud/security/allow-ip-address.html[IP address is whitelisted]
- ensure that you have a https://docs.couchbase.com/cloud/security/manage-database-users.html[database user]
- Populate the relevant cluster section in the `config` file with the public address and database user credentials.

[#_management_commands]
=== Management Commands

Management commands (such as `cluster` and `bucket` management) require a specific section to be added to the `config` file as well as an extra entry in the relevant cluster section.
Before being able to perform management operations against Couchbase Capella you must https://docs.couchbase.com/cloud/public-api-guide/using-cloud-public-api.html#access-and-secret-keys[generate access and secret keys] to enable Couchbase Shell to interact with your Capella organisation.

=== Config file format

The `capella-organisation` section in the `config` file is used as follows:

[source,toml]
----
# Allows us to evolve in the future without breaking old config files
version = 1

[[database]]
identifier = "default"
conn-string = "127.0.0.1"
default-bucket = "travel-sample"
# The following can be part of the config or credentials
username = "Administrator"
password = "password"

[[database]]
# identifier *must* match the name of the cluster as provided in Couchbase Cloud
identifier = "capellahostedcluster"
conn-string = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.dp.cloud.couchbase.com"
default-bucket = "couchbasecloudbucket"
username = "dave"
password = "Pa55word!"
data-timeout = "25s"
query-timeout = "1m 15s"
tls-enabled = true
tls-validate-hostnames = false
tls-accept-all-certs = true
capella-organisation = "myhostedorg"

[[capella-organisation]]
identifier = "myhostedorg"
access-key = "x8rLuZ3YBNEqPfb8whKHxt0v9wxf1pdG"
secret-key = "T26Rh3zRaUYFIzdRQfbdPxSQN7bxJatE2jgg1JDQqZ1yyqwGUZt7nx2E6w1yzosY"
default-project = "mydefaultproject"

----

Note that the identifier of the cluster *must* match the corresponding names in Couchbase Capella for management operations to succeed.
Also note that some operations are not supported by Couchbase Capella.
