[#_cb_env_and_the_environment]
== `cb-env` and the Environment

Whilst multiple databases can be registered at the same time, there is only ever one database (at most) active.
The same is true for buckets, scopes, and collections.
When a resource is active then it used as the default to run commands against (this can be overridden on a per command basis).

You can run the `cb-env` command, which will tell you which resources are currently active (you are also able to tell from the prompt):

```
> cb-env
╭──────────────┬─────────────╮
│ username     │ charlie     │
│ display_name │ Charlie     │
│ database     │ capella     │
│ bucket       │ default     │
│ scope        │ inventory   │
│ collection   │ hotel       │
│ cluster_type │ provisioned │
╰──────────────┴─────────────╯
```

If you were to now run a command then we would be running it:

* As the user "charlie"
* Against the "capella" database
* Against the "default" bucket
* Against the "inventory" scope
* Against the "hotel" collection

Npte that `display_name` is the name that appears in your shell prompt and is not used by commands.

You can also change the active resources with the `cb-env` command.

```
> cb-env -h
Modify the default execution environment of commands

Usage:
  > cb-env {flags}

Subcommands:
  cb-env bucket - Sets the active bucket based on its name
  cb-env capella-organization - Sets the active capella organization based on its identifier
  cb-env collection - Sets the active collection based on its name
  cb-env database - Sets the active database based on its identifier
  cb-env managed - Lists all databases currently managed by couchbase shell
  cb-env project - Sets the active project based on its name
  cb-env register - Registers a database for use with the shell
  cb-env scope - Sets the active scope based on its name
  cb-env timeouts - Sets the active timeouts for operations
  cb-env unregister - Registers a database for use with the shell

Flags:
  -h, --help - Display the help message for this command
  --capella - show default execution environment of capella
  --timeouts - show default execution environment for timeouts
```

For example if you change the active bucket:

```
> cb-env bucket beer-sample
╭────────┬─────────────╮
│ bucket │ beer-sample │
╰────────┴─────────────╯
```

```
> cb-env
╭──────────────┬─────────────╮
│ username     │ charlie     │
│ display_name │ Charlie     │
│ database     │ capella     │
│ bucket       │ beer-sample │
│ scope        │ inventory   │
│ collection   │ hotel       │
│ cluster_type │ provisioned │
╰──────────────┴─────────────╯
```

Both the output of `cb-env` and the prompt will reflect the changes.

=== Per command execution environments

On many commands you will notice a set of flags which allow you to override the active execution environment.
Different commands support different flags, depending on the command you can expect to see any of:

* `--databases`
* `--bucket`
* `--scope`
* `--collection`

==== The `--databases` flag

The argument for this flag is an identifier combined with a regular expression.
So imagine you have three databases setup with the following names:

```
> cb-env | get database
───┬────────
 0 │ prod-us-west
 1 │ prod-us-east
 2 │ prod-eu-center
 3 │ local-test
───┴────────
```

If you wanted to run a command against all databases in `prod-us`, you could use `--databases prod-us.*`, e.g.

```
> buckets --databases prod-us.*
───┬──────────────┬───────────────┬───────────┬──────────┬──────────────────────┬───────────┬───────────────┬────────┬───────
 # │   database   │     name      │   type    │ replicas │ min_durability_level │ ram_quota │ flush_enabled │ status │ capella
───┼──────────────┼───────────────┼───────────┼──────────┼──────────────────────┼───────────┼───────────────┼────────┼───────
 0 │ prod-us-east │ default       │ couchbase │        1 │ none                 │  268.4 MB │ false         │        │ false
 1 │ prod-us-west │ default       │ couchbase │        1 │ none                 │  268.4 MB │ false         │        │ false
 2 │ prod-us-west │ travel-sample │ couchbase │        1 │ none                 │  209.7 MB │ false         │        │ false
───┴──────────────┴───────────────┴───────────┴──────────┴──────────────────────┴───────────┴───────────────┴────────┴───────
```

In the background this gets passed to a regex engine, so you can go a little crazy with it if needed.

==== The `--bucket`, `--scope`, `--collection` flags

These flags are a little different to the `--databases` flag, they are not regular expressions and can only be used to define a single name each.
Unlike `--databases` the name provided to these flags does not have to be already known to Couchbase Shell, they can refer to any bucket, scope, and collection that exist within your active database or defined database(s).
For example:

```
> doc get 1 --bucket travel-sample --scope tenant_agent_00 --collection users
───┬────┬─────────────────────┬──────────────────┬───────┬──────────────
 # │ id │         cas         │     content      │ error │   database
───┼────┼─────────────────────┼──────────────────┼───────┼──────────────
 0 │ 1  │ 1638870288919035904 │ [row 11 columns] │       │ prod-us-west
───┴────┴─────────────────────┴──────────────────┴───────┴──────────────
```


