[#_cb_env_and_the_environment]
== `cb-env` and the Environment

Whilst multiple clusters can be registered at the same time, there is only ever one cluster (at most) active.
The same is true for buckets, scopes, and collections.
When a resource is active then it used as the default to run commands against (this can be overridden on a per command basis).

You can run the `cb-env` command, which will tell you which resources are currently active (you are also able to tell from the prompt):

```
> cb-env
â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ username     â”‚ charlie     â”‚
â”‚ display_name â”‚ Charlie     â”‚
â”‚ cluster      â”‚ capella     â”‚
â”‚ bucket       â”‚ default     â”‚
â”‚ scope        â”‚ inventory   â”‚
â”‚ collection   â”‚ hotel       â”‚
â”‚ cluster_type â”‚ provisioned â”‚
â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

If you were to now run a command then we would be running it:

* As the user "charlie"
* Against the "capella" cluster
* Against the "default" bucket
* Against the "inventory" scope
* Against the "hotel" collection

Note that `display_name` is the name that appears in your shell prompt and is not used by commands.

You can also change the active resources with the `cb-env` command.

```
> cb-env -h
Modify the default execution environment of commands

Usage:
  > cb-env {flags}

Subcommands:
  cb-env bucket - Sets the active bucket based on its name
  cb-env capella-organization - Sets the active capella organization based on its identifier
  cb-env cluster - Sets the active cluster based on its identifier
  cb-env collection - Sets the active collection based on its name
  cb-env managed - Lists all clusters currently managed by couchbase shell
  cb-env project - Sets the active project based on its name
  cb-env register - Registers a cluster for use with the shell
  cb-env scope - Sets the active scope based on its name
  cb-env timeouts - Sets the active timeouts for operations
  cb-env unregister - Unregisters a cluster for use with the shell

Flags:
  -h, --help - Display the help message for this command
  --capella - show default execution environment of capella
  --timeouts - show default execution environment for timeouts
```

For example if you change the active bucket both the output of `cb-env` and the prompt will reflect the changes:

```
ðŸ‘¤ Charlie ðŸ  local
> cb-env bucket beer-sample
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ beer-sample._default._default
> cb-env
â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ username     â”‚ charlie       â”‚
â”‚ display_name â”‚ Charlie       â”‚
â”‚ cluster      â”‚ capella       â”‚
â”‚ bucket       â”‚ beer-sample   â”‚
â”‚ scope        â”‚               â”‚
â”‚ collection   â”‚               â”‚
â”‚ cluster_type â”‚ provisioned   â”‚
â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

=== Per command execution environments

On many commands you will notice a set of flags which allow you to override the active execution environment.
Different commands support different flags, depending on the command you can expect to see any of:

* `--clusters`
* `--bucket`
* `--scope`
* `--collection`

==== The `--clusters` flag

The argument for this flag is an identifier combined with a regular expression.
So imagine you have three clusters setup with the following names:

```
> cb-env managed | get identifier
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ 0 â”‚ prod-us-east   â”‚
â”‚ 1 â”‚ prod-us-west   â”‚
â”‚ 2 â”‚ prod-eu-center â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

If you wanted to run a command against all clusters in `prod-us`, you could use `--clusters prod-us.*`, e.g.

[options="nowrap"]
```
> buckets --clusters prod-us.*
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚   cluster    â”‚     name      â”‚   type    â”‚ replicas â”‚ min_durability_level â”‚ ram_quota â”‚ flush_enabled â”‚ status â”‚ cloud â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ prod-us-east â”‚ default       â”‚ couchbase â”‚        1 â”‚ none                 â”‚ 200.0 MiB â”‚ false         â”‚        â”‚ false â”‚
â”‚ 1 â”‚ prod-us-west â”‚ default       â”‚ couchbase â”‚        1 â”‚ none                 â”‚ 200.0 MiB â”‚ false         â”‚        â”‚ false â”‚
â”‚ 2 â”‚ prod-us-west â”‚ travel-sample â”‚ couchbase â”‚        1 â”‚ none                 â”‚ 200.0 MiB â”‚ false         â”‚        â”‚ false â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â•¯
```

In the background this gets passed to a regex engine, so you can go a little crazy with it if needed.

==== The `--bucket`, `--scope`, `--collection` flags

These flags are a little different to the `--clusters` flag, they are not regular expressions and can only be used to define a single name each.
Unlike `--clusters` the name provided to these flags does not have to be already known to Couchbase Shell, they can refer to any bucket, scope, and collection that exist within your active cluster or defined cluster(s).
For example:

[options="nowrap"]
```
> doc get 1 --bucket travel-sample --scope tenant_agent_00 --collection users
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ id â”‚                                        content                                        â”‚         cas         â”‚ error â”‚   cluster    â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ 1  â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ 1712321628245917696 â”‚       â”‚ prod-us-west â”‚
â”‚   â”‚    â”‚ â”‚ name              â”‚ Rigoberto Bernier                                             â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ addresses         â”‚ â”‚ # â”‚ type â”‚     address      â”‚    city    â”‚    country     â”‚ â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤ â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â”‚ 0 â”‚ home â”‚ 0622 Adams Mills â”‚ Manchester â”‚ United Kingdom â”‚ â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ driving_licence   â”‚ 5f5f145d-a4db-5630-b7d8-874df29a505d                          â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ passport          â”‚ a1c4f1ac-a7d7-5b97-88ed-11cafc634896                          â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ preferred_email   â”‚ rigobertobernier@gadugca.sd                                   â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ preferred_phone   â”‚ (965) 227-3977                                                â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ preferred_airline â”‚ inventory.airline.airline_5479                                â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ preferred_airport â”‚ inventory.airport.airport_478                                 â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®       â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ credit_cards      â”‚ â”‚ # â”‚       type       â”‚     number      â”‚ expiration â”‚       â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤       â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â”‚ 0 â”‚ American Express â”‚ 346533746753899 â”‚ 2021-04    â”‚       â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯       â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ created           â”‚ 2020-04-12                                                    â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ updated           â”‚ 2021-02-19                                                    â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚                     â”‚       â”‚              â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```


