[#_cb_env_and_the_environment]
== `cb-env` and the Environment

Whilst multiple clusters can be registered at the same time, there is only ever one cluster (at most) active.
The same is true for buckets, scopes, and collections.
When a resource is active it is used as the default to run commands against (this can be overridden on a <<_per_command_execution_environments,per command>> basis).

The `cb-env` command will tell you which resources are currently active (you are also able to tell from the <<_the_prompt_explained,prompt>>):
```
> cb-env
â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ username             â”‚ charlie      â”‚
â”‚ display_name         â”‚ Charlie      â”‚
â”‚ cluster              â”‚ capella      â”‚
â”‚ bucket               â”‚ default      â”‚
â”‚ scope                â”‚ inventory    â”‚
â”‚ collection           â”‚ hotel        â”‚
â”‚ cluster_type         â”‚ provisioned  â”‚
â”‚ capella-organization â”‚ couchbase    â”‚
â”‚ capella-project      â”‚ Charlie work â”‚
â”‚ llm                  â”‚ Gemini       â”‚
â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```
If you were to now run a command then we would be running it:

* As the user "charlie"
* Against the "capella" cluster
* Against the "default" bucket
* Against the "inventory" scope
* Against the "hotel" collection

Note that `display_name` is the name that appears in your shell prompt and is not used by commands.

You can also change the active resources with the cb-env command.
```
> cb-env -h
Modify the default execution environment of commands

Usage:
  > cb-env {flags}

Subcommands:
  cb-env bucket - Sets the active bucket based on its name
  cb-env capella-organization - Sets the active capella organization based on its identifier
  cb-env cluster - Sets the active cluster based on its identifier
  cb-env collection - Sets the active collection based on its name
  cb-env managed - Lists all clusters currently managed by couchbase shell
  cb-env project - Sets the active project based on its name
  cb-env register - Registers a cluster for use with the shell
  cb-env scope - Sets the active scope based on its name
  cb-env timeouts - Sets the active timeouts for operations
  cb-env unregister - Unregisters a cluster for use with the shell

Flags:
  -h, --help - Display the help message for this command
  --capella - show default execution environment of capella
  --timeouts - show default execution environment for timeouts
```

=== `cb-env managed`

Lists all the clusters you have registered with the shell.

```
> cb-env managed
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ active â”‚  tls  â”‚ identifier â”‚   username    â”‚ capella_organization â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ true   â”‚ false â”‚ dev.local  â”‚ Administrator â”‚                      â”‚
â”‚ 1 â”‚ false  â”‚ true  â”‚ capella    â”‚ charlie       â”‚                      â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

=== `cb-env cluster`

Changes the active cluster.
The change of cluster will be reflected in the output of `cb-env` and the prompt:

```
ðŸ‘¤ Charlie ðŸ  capella
> cb-env cluster local
ðŸ‘¤ Charlie ðŸ  local
> cb-env
â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ username     â”‚ charlie       â”‚
â”‚ display_name â”‚ Charlie       â”‚
â”‚ cluster      â”‚ local         â”‚
â”‚ bucket       â”‚               â”‚
â”‚ scope        â”‚               â”‚
â”‚ collection   â”‚               â”‚
â”‚ cluster_type â”‚ other         â”‚
â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```
Notice that when you are connected to a locally running (non-Capella) cluster then the capella specific fields (project and capella organization) will not appear.

When changing the cluster the shell will return an error if a cluster with the given identifier is not registered:
```
> cb-env cluster unregistered
Error:   Ã— The cluster named unregistered is not known
```

To register a new cluster for use either add it to the <<_the_config_dotfiles,config file>> or use the <<_cb_env_register,cb-env register>> command.

=== `cb-env bucket/scope/collection`

The `cb-env bucket`, `cb-env scope` and `cb-env collection` commands are used to set the active bucket/scope/collection respectively.
When changing the bucket/scope/collection the change will be reflected in the <<_the_prompt_explained,prompt>> and the output of the <<_cb_env_and_the_environment,cb-env>> command:

```
ðŸ‘¤ Charlie ðŸ  local
> cb-env bucket travel-sample
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample._default._default
> cb-env scope inventory
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample.inventory._default
> cb-env collection landmark
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample.inventory.landmark
>
```

Note that when we set an active bucket the scope and collection are set to the `_default` scope and collection.

When a "higher level" entity is changed the "lower level" entities are returned to this default setting:

```
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample.inventory.landmarks
> cb-env scope some_scope
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ travel-sample.some_scope._default
> cb-env bucket some_bucket
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ some_bucket._default._default
>
```

Setting the scope resets the collection and setting the bucket will reset both the scope and collection.
It is important to remember that these commands do not validate the existence of resources when the environment is changed.
Setting the active bucket/scope/collection to one that doesn't exist will only have an impact when you try and perform operations against it.

[options="nowrap"]
```
ðŸ‘¤ Charlie ðŸ  local
> cb-env bucket not-a-real-bucket
ðŸ‘¤ Charlie ðŸ  local in ðŸ—„ not-a-real-bucket._default._default
> doc get test_doc
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ id â”‚ content â”‚ cas â”‚                                    error                                     â”‚ cluster â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚    â”‚         â”‚   0 â”‚ Failed to load cluster config: bucket 'not-a-real-bucket' could not be found â”‚ local   â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Checking that the active environment is correctly set to resources that exist is a good first port of call if things aren't working as expected.

=== `cb-env project/capella-organization`

The highest level entity in Capella is the organization. Within this you have projects which in turn contain clusters.
Although you can connect to a Capella cluster without it having an <<_the_config_dotfiles,organization registered>> an organization is required to perform management operations: creating/destroying projects/clusters/buckets.

Once we have a registered organization we can set it as active in two ways. Manually, by using the `cb-env capella-organization` command:

```
> cb-env capella-organization my-org
```

Or if you switch to an active cluster that has a default Capella organization specified on registration then that org will become active.
The logic is similar with the active project which can either be changed manually:

```
ðŸ‘¤ Administrator ðŸ  local in ðŸ—„ default._default._default
> cb-env project my-project
```

Alternatively if the active organization has a default project defined on registration then that default project will become active.
Similarly to changing active clusters, the `cb-env capella-organization` command will return an error if the named org has not been registered with the shell:

```
> cb-env capella-organization not-an-org
Error:   Ã— Organization not registered
  help: Has the organization not-an-org been registered in the config file?
```

But the same is not true with projects, so if operations are unexpectedly failing against a Capella cluster, make sure your active project is correctly set.

=== `cb-env register`

```
> cb-env register --help
Registers a cluster for use with the shell

Usage:
  > cb-env register {flags} <identifier> <connstr> <username> <password>

Flags:
  -h, --help - Display the help message for this command
  --display_name <String> - the display name to use for the user when this cluster is active
  --default-bucket <String> - the default bucket to use with this cluster
  --default-scope <String> - the default scope to use with this cluster
  --default-collection <String> - the default collection to use with this cluster
  --tls-enabled <String> - whether or not to enable tls, defaults to true
  --tls-cert-path <String> - the path to the certificate to use with tls
  --tls-accept-all-certs <String> - whether or not to accept all certs with tls, defaults to true
  --save - whether or not to add the cluster to the .cbsh config file, defaults to false
  --capella-organization <String> - capella organization that this cluster belongs to

Parameters:
  identifier <string>: the identifier to use for this cluster
  connstr <string>: the connection string to use for this cluster
  username <string>: the username to use for this cluster
  password <string>: the password to use for this cluster
```

This command registers a new cluster for use with the shell without having to add a `cluster` entry to the <<_the_config_dotfiles,config file>> and restart.
Note that clusters created through the shell using `clusters create` are automatically registered for use.
`cb-env register` takes the local identifier for the cluster, connection string, username and password as positional parameters:

```
ðŸ‘¤ Charlie ðŸ  remote in â˜ï¸ default._default._default
> cb-env register new-cluster cb.lcrhwge7pstmolxx.couchbase.com Administrator password
```

Once registered the new cluster can be seen in the output of `cb-env managed`, and can be set as the active cluster using <<_cb_env_cluster,cb-env cluster>>:

```
ðŸ‘¤ Charlie ðŸ  remote in â˜ï¸ default._default._default
> cb-env managed
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ active â”‚  tls  â”‚ identifier  â”‚   username    â”‚ capella_organization â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ false  â”‚ false â”‚ local       â”‚ Administrator â”‚                      â”‚
â”‚ 1 â”‚ false  â”‚ true  â”‚ new-cluster â”‚ Administrator â”‚                      â”‚
â”‚ 2 â”‚ true   â”‚ true  â”‚ remote      â”‚ charlie       â”‚ my-org               â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

Note that by default although tls is enabled the shell will accept all certs. This can be changed with the `--tls-accept-all-certs` flag.

=== `cb-env llm`

```
> cb-env llm --help
Sets the active llm based on its identifier

Usage:
  > cb-env llm <identifier>

Flags:
  -h, --help - Display the help message for this command

Parameters:
  identifier <string>: the identifier of the llm
```

This command sets the active llm (large language model), which will be used by the <<_vector_enrich_doc,vector enrich-doc>>, <<_vector_enrich_text,vector enrich-text>> and <<_ask,ask>> commands.

To be set as active the llm must be specified in the config file.
For example:

```
[[llm]]
identifier = "OpenAI-small"
provider = "OpenAI"
embed_model = "text-embedding-3-small"
chat_model = "gpt-3.5-turbo"
api_key = "get-your-own"

[[llm]]
identifier = "Bedrock-titan"
provider = "Bedrock"
embed_model = "amazon.titan-embed-text-v1"
chat_model = "amazon.titan-text-express-v1"

[[llm]]
identifier = "Gemini-pro"
provider = "Gemini"
embed_model = "text-embedding-004"
chat_model = "gemini-1.0-pro"
api_key = "get-your-own"
```

The currently supported providers are Gemini (Google), Bedrock (AWS) and OpenAI.
Specifying values other than these for the provider will result in an error when starting the shell.
Notice that the Bedrock entry does not have an API key, this is because it requires the user to configure an appropriate role using the https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-role.html[AWS CLI].

The `embed-model` field is the model that will be used to generate embeddings by the <<_vector_enrich_doc,vector enrich-doc>> and <<_vector_enrich_text,vector enrich-text>> commands.
While the `chat-model` is the model that will be used to answer questions with the <<_ask,ask>> command.
These models can be any that the provider's API supports, and should be provided in the format given in the provider's API docs.

The api-keys can also be given separately in the <<_credentials_file_format,credentials file>>, for example:

```
[[llm]]
identifier = "Gemini-pro"
api_key = "get-your-own"
```

The identifier must be the same as the entry in the config file for this to work.

The active llm can be checked using the <<_cb_env_and_the_environment,cb-env>> command:

```
ðŸ‘¤ Charlie ðŸ  remote in â˜ï¸ default._default._default
> cb-env
â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ username             â”‚ Administrator â”‚
â”‚ display_name         â”‚ Charlie       â”‚
â”‚ cluster              â”‚ remote        â”‚
â”‚ bucket               â”‚ default       â”‚
â”‚ scope                â”‚ _default      â”‚
â”‚ collection           â”‚ _default      â”‚
â”‚ cluster_type         â”‚ provisioned   â”‚
â”‚ capella-organization â”‚ my-org        â”‚
â”‚ llm                  â”‚ Bedrock-titan â”‚
â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

When the active llm is changed using `cb-env llm` this will be reflected in the output of `cb-env`:

```
> cb-env llm Gemini-pro
ðŸ‘¤ Charlie ðŸ  remote in â˜ï¸ default._default._default
> cb-env
â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ username             â”‚ Administratorâ”‚
â”‚ display_name         â”‚ Charlie      â”‚
â”‚ cluster              â”‚ remote       â”‚
â”‚ bucket               â”‚ default      â”‚
â”‚ scope                â”‚ _default     â”‚
â”‚ collection           â”‚ _default     â”‚
â”‚ cluster_type         â”‚ provisioned  â”‚
â”‚ capella-organization â”‚ my-org       â”‚
â”‚ llm                  â”‚ Gemini-pro   â”‚
â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```




=== Per command execution environments

On many commands you will notice a set of flags which allow you to override the active execution environment.
Different commands support different flags, depending on the command you can expect to see any of:

* `--clusters`
* `--bucket`
* `--scope`
* `--collection`

==== The `--clusters` flag

The argument for this flag is an identifier combined with a regular expression.
So imagine you have three clusters setup with the following names:

```
> cb-env managed | get identifier
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ 0 â”‚ prod-us-east   â”‚
â”‚ 1 â”‚ prod-us-west   â”‚
â”‚ 2 â”‚ prod-eu-center â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

If you wanted to run a command against all clusters in `prod-us`, you could use `--clusters prod-us.*`, e.g.

[options="nowrap"]
```
> buckets --clusters prod-us.*
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚   cluster    â”‚     name      â”‚   type    â”‚ replicas â”‚ min_durability_level â”‚ ram_quota â”‚ flush_enabled â”‚ status â”‚ cloud â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ prod-us-east â”‚ default       â”‚ couchbase â”‚        1 â”‚ none                 â”‚ 200.0 MiB â”‚ false         â”‚        â”‚ false â”‚
â”‚ 1 â”‚ prod-us-west â”‚ default       â”‚ couchbase â”‚        1 â”‚ none                 â”‚ 200.0 MiB â”‚ false         â”‚        â”‚ false â”‚
â”‚ 2 â”‚ prod-us-west â”‚ travel-sample â”‚ couchbase â”‚        1 â”‚ none                 â”‚ 200.0 MiB â”‚ false         â”‚        â”‚ false â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â•¯
```

In the background this gets passed to a regex engine, so you can go a little crazy with it if needed.

==== The `--bucket`, `--scope`, `--collection` flags

These flags are a little different to the `--clusters` flag, they are not regular expressions and can only be used to define a single name each.
Unlike `--clusters` the name provided to these flags does not have to be already known to Couchbase Shell, they can refer to any bucket, scope, and collection that exist within your active cluster or defined cluster(s).
For example:

[options="nowrap"]
```
> doc get 1 --bucket travel-sample --scope tenant_agent_00 --collection users
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ id â”‚                                        content                                        â”‚         cas         â”‚ error â”‚   cluster    â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚ 1  â”‚ â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ 1712321628245917696 â”‚       â”‚ prod-us-west â”‚
â”‚   â”‚    â”‚ â”‚ name              â”‚ Rigoberto Bernier                                             â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•® â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ addresses         â”‚ â”‚ # â”‚ type â”‚     address      â”‚    city    â”‚    country     â”‚ â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤ â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â”‚ 0 â”‚ home â”‚ 0622 Adams Mills â”‚ Manchester â”‚ United Kingdom â”‚ â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ driving_licence   â”‚ 5f5f145d-a4db-5630-b7d8-874df29a505d                          â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ passport          â”‚ a1c4f1ac-a7d7-5b97-88ed-11cafc634896                          â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ preferred_email   â”‚ rigobertobernier@gadugca.sd                                   â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ preferred_phone   â”‚ (965) 227-3977                                                â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ preferred_airline â”‚ inventory.airline.airline_5479                                â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ preferred_airport â”‚ inventory.airport.airport_478                                 â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®       â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ credit_cards      â”‚ â”‚ # â”‚       type       â”‚     number      â”‚ expiration â”‚       â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤       â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â”‚ 0 â”‚ American Express â”‚ 346533746753899 â”‚ 2021-04    â”‚       â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚                   â”‚ â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯       â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ created           â”‚ 2020-04-12                                                    â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â”‚ updated           â”‚ 2021-02-19                                                    â”‚ â”‚                     â”‚       â”‚              â”‚
â”‚   â”‚    â”‚ â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯ â”‚                     â”‚       â”‚              â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```


