== Couchbase Capella (DBaaS)

https://cloud.couchbase.com/sign-up?ref=cbsh-web-capella[Couchbase Capella] is a Database as a Service offering from Couchbase which you can interact with from Couchbase Shell.

=== `use`  and the Environment

For general usage of the `use` command see <<_use_and_the_environment>>.
When using <<_management_commands>> with Couchbase Capella and Couchbase Shell we need to be able to manage more active resources than the base `use` command gives us.
You can use the `use --capella` command to see which cloud resources are current active:

```
> use --capella
──────────────────────┬──────────────────
 capella-organization │ mycapellaorg
 cloud                │
 project              │ mycapellaproject
──────────────────────┴──────────────────
```

The active resource can be changed with the `use` command:

```
> use -h
Modify the default execution environment of commands

Usage:
  > use <subcommand> {flags}

Subcommands:
  use bucket - Sets the active bucket based on its name
  use cloud - Sets the active cloud based on its identifier
  use capella-organization - Sets the active capella organization based on its identifier
  use cluster - Sets the active cluster based on its identifier
  use collection - Sets the active collection based on its name
  use project - Sets the active project based on its name
  use scope - Sets the active scope based on its name
```

=== Document Level Commands

Document level commands like those under `doc`, `analytics`, `query`, and `search` (with a couple of exceptions) do not require any special changes to the `config` config file.

You need to:

    - https://docs.couchbase.com/cloud/clusters/create-cluster.html[create a cluster] in your Couchbase Capella account
    - ensure that your https://docs.couchbase.com/cloud/security/allow-ip-address.html[IP address is whitelisted]
    - ensure that you have a https://docs.couchbase.com/cloud/security/manage-database-users.html[database user]
    - Populate the relevant cluster section in the `config` file with the public address and database user credentials.

=== Management Commands

Management commands (such as `cluster` and `bucket` management) require a specific section to be added to the `config` file as well as an extra entry in the relevant cluster section.
Before being able to perform management operations against Couchbase Capella you must https://docs.couchbase.com/cloud/public-api-guide/using-cloud-public-api.html#access-and-secret-keys[generate access and secret keys] to enable Couchbase Shell to interact with your Capella organisation.

=== Config file format

The `capella-organisation` section in the `config` file is used as follows:

[source,toml]
----
# Allows us to evolve in the future without breaking old config files
version = 1

[[cluster]]
identifier = "default"
hostnames = ["127.0.0.1"]
default-bucket = "travel-sample"
# The following can be part of the config or credentials
username = "Administrator"
password = "password"

[[cluster]]
# identifier *must* match the name of the cluster as provided in Couchbase Cloud
identifier = "capellahostedcluster"
hostnames = ["xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.dp.cloud.couchbase.com"]
default-bucket = "couchbasecloudbucket"
username = "dave"
password = "Pa55word!"
data-timeout = "25s"
query-timeout = "1m 15s"
tls-enabled = true
tls-validate-hostnames = false
tls-accept-all-certs = true
capella-organisation = "myhostedorg"

[[capella-organisation]]
identifier = "myhostedorg"
access-key = "x8rLuZ3YBNEqPfb8whKHxt0v9wxf1pdG"
secret-key = "T26Rh3zRaUYFIzdRQfbdPxSQN7bxJatE2jgg1JDQqZ1yyqwGUZt7nx2E6w1yzosY"
default-project = "mydefaultproject"
# The environment field defaults to "hosted" so we don't have to include it here.

[[capella-organisation]]
identifier = "myinvpcorg"
access-key = "x8rLuZ3YBNEqPfb8whKHxt0v9wxf1pdG"
secret-key = "T26Rh3zRaUYFIzdRQfbdPxSQN7bxJatE2jgg1JDQqZ1yyqwGUZt7nx2E6w1yzosY"
default-project = "mydefaultproject"
default-cloud = "mydefaultcloud"
environment = "in-vpc"

----

Note that the identifier of the cluster, and the default-cloud (if applicable) *must* match the corresponding names in Couchbase Capella for management operations to work.
Also note that some operations are not supported by Couchbase Capella.
