== Couchbase Commands

The following sections discuss the individual couchbase specific commands in greater detail. Remember, you can always mix and match them with built-in other shell commands as well as executables from your environment.

=== Working with `clusters`

The `clusters` command lists all the clusters you specified in your configuration and the shell might be connected to.

```
> clusters
───┬────────┬─────┬────────────┬───────────────
 # │ active │ tls │ identifier │ username      
───┼────────┼─────┼────────────┼───────────────
 0 │ No     │ No  │ local      │ Administrator 
 1 │ Yes    │ No  │ remote     │ Administrator
───┴────────┴─────┴────────────┴───────────────
```

=== Working with `buckets`

The `buckets` command lists all the buckets from your active cluster:

```
> buckets
───┬─────────┬───────────────┬───────────┬──────────┬────────────────┬─────────────
 # │ cluster │     name      │   type    │ replicas │ quota_per_node │ quota_total
───┼─────────┼───────────────┼───────────┼──────────┼────────────────┼─────────────
 0 │ default │ beer-sample   │ couchbase │        1 │       104.9 MB │    104.9 MB
 1 │ default │ default       │ couchbase │        1 │       104.9 MB │    104.9 MB
 2 │ default │ memd          │ memcached │        0 │       104.9 MB │    104.9 MB
 3 │ default │ travel-sample │ couchbase │        1 │       104.9 MB │    104.9 MB
───┴─────────┴───────────────┴───────────┴──────────┴────────────────┴─────────────
```

As an advanced command, it is also possible to get the configuration for a bucket:

```
> buckets config beer-sample
────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────
 name                   │ beer-sample                                                                              
 uuid                   │ 0af4496fe0612c76885d5dcd3e010c0d                                                         
 bucketType             │ membase                                                                                  
 authType               │ sasl                                                                                     
 uri                    │ /pools/default/buckets/beer-sample?bucket_uuid=0af4496fe0612c76885d5dcd3e010c0d          
 streamingUri           │ /pools/default/bucketsStreaming/beer-sample?bucket_uuid=0af4496fe0612c76885d5dcd3e010c0d 
 localRandomKeyUri      │ /pools/default/buckets/beer-sample/localRandomKey                                        
 controllers            │ [row compactAll compactDB purgeDeletes startRecovery]                                    
 nodes                  │ [table 1 rows]                                                                           
 stats                  │ [row directoryURI nodeStatsListURI uri]                                                  
 nodeLocator            │ vbucket                                                                                  
 saslPassword           │ 7fd7338a6b8fb30dbfb80205834db634                                                         
 ddocs                  │ [row uri]                                                                                
 replicaIndex           │ Yes                                                                                      
 autoCompactionSettings │ No                                                                                       
 vBucketServerMap       │ [row hashAlgorithm numReplicas serverList vBucketMap]                                    
 maxTTL                 │ 0                                                                                        
 compressionMode        │ passive                                                                                  
 replicaNumber          │ 1                                                                                        
 threadsNumber          │ 3                                                                                        
 quota                  │ [row ram rawRAM]                                                                         
 basicStats             │ [row 8 columns]                                                                          
 evictionPolicy         │ valueOnly                                                                                
 conflictResolutionType │ seqno                                                                                    
 bucketCapabilitiesVer  │                                                                                          
 bucketCapabilities     │ [table 9 rows]                                                                           
────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────
```

If you are unsure what you would use this for, you probably don't need it.
If you have pivot mode (detailed above) turned off then this command can produce results that are difficult to read.

=== Working with `scopes` and `collections`

The `scopes` and `collections` commands can be used for managing scopes and collection respectively.

==== Scopes

```
> scopes -h
Fetches scopes through the HTTP API

Usage:
  > scopes <subcommand> {flags}

Subcommands:
  scopes create - Creates scopes through the HTTP API
  scopes drop - Deletes scopes through the HTTP API

Flags:
  -h, --help: Display this help message
  --bucket <string>: the name of the bucket
  --clusters <string>: the clusters to query against
```

To list all scopes in the bucket you would use:

```
> scopes
───┬─────────────────┬──────────────
 # │      scope      │   cluster
───┼─────────────────┼──────────────
 0 │ inventory       │ prod-us-west
 1 │ tenant_agent_00 │ prod-us-west
 2 │ tenant_agent_01 │ prod-us-west
 3 │ tenant_agent_02 │ prod-us-west
 4 │ tenant_agent_03 │ prod-us-west
 5 │ tenant_agent_04 │ prod-us-west
 6 │ _default        │ prod-us-west
───┴─────────────────┴──────────────
```

You can also create and remove scopes:

```
> scopes create tenant_agent_05
> scopes
───┬─────────────────┬──────────────
# │      scope      │   cluster
───┼─────────────────┼──────────────
0 │ tenant_agent_05 │ prod-us-west
1 │ inventory       │ prod-us-west
2 │ tenant_agent_00 │ prod-us-west
3 │ tenant_agent_01 │ prod-us-west
4 │ tenant_agent_02 │ prod-us-west
5 │ tenant_agent_03 │ prod-us-west
6 │ tenant_agent_04 │ prod-us-west
7 │ _default        │ prod-us-west
───┴─────────────────┴──────────────
```

```
> scopes drop tenant_agent_05
> scopes
───┬─────────────────┬──────────────
 # │      scope      │   cluster
───┼─────────────────┼──────────────
 0 │ inventory       │ prod-us-west
 1 │ tenant_agent_00 │ prod-us-west
 2 │ tenant_agent_01 │ prod-us-west
 3 │ tenant_agent_02 │ prod-us-west
 4 │ tenant_agent_03 │ prod-us-west
 5 │ tenant_agent_04 │ prod-us-west
 6 │ _default        │ prod-us-west
───┴─────────────────┴──────────────
```

==== Collections

```
> collections -h
Fetches collections through the HTTP API

Usage:
  > collections <subcommand> {flags}

Subcommands:
  collections create - Creates collections through the HTTP API
  collections drop - Deletes collections through the HTTP API

Flags:
  -h, --help: Display this help message
  --bucket <string>: the name of the bucket
  --scope <string>: the name of the scope
  --clusters <string>: the clusters to query against
```

To list all collection in the bucket you would use:

```
> collections
────┬─────────────────┬────────────┬────────────┬──────────────
 #  │      scope      │ collection │ max_expiry │   cluster
────┼─────────────────┼────────────┼────────────┼──────────────
  0 │ inventory       │ hotel      │ 0sec       │ prod-us-west
  1 │ inventory       │ airport    │ 0sec       │ prod-us-west
  2 │ inventory       │ airline    │ 0sec       │ prod-us-west
  3 │ inventory       │ route      │ 0sec       │ prod-us-west
  4 │ inventory       │ landmark   │ 0sec       │ prod-us-west
  5 │ tenant_agent_00 │ users      │ 0sec       │ prod-us-west
  6 │ tenant_agent_00 │ bookings   │ 0sec       │ prod-us-west
  7 │ tenant_agent_01 │ bookings   │ 0sec       │ prod-us-west
  8 │ tenant_agent_01 │ users      │ 0sec       │ prod-us-west
  9 │ tenant_agent_02 │ users      │ 0sec       │ prod-us-west
 10 │ tenant_agent_02 │ bookings   │ 0sec       │ prod-us-west
 11 │ tenant_agent_03 │ users      │ 0sec       │ prod-us-west
 12 │ tenant_agent_03 │ bookings   │ 0sec       │ prod-us-west
 13 │ tenant_agent_04 │ bookings   │ 0sec       │ prod-us-west
 14 │ tenant_agent_04 │ users      │ 0sec       │ prod-us-west
 15 │ _default        │ _default   │ 0sec       │ prod-us-west
────┴─────────────────┴────────────┴────────────┴──────────────
```

You can also create and remove collections:

```
> collections create staff --scope tenant_agent_00
> collections --scope tenant_agent_00
───┬─────────────────┬────────────┬────────────┬──────────────
 # │      scope      │ collection │ max_expiry │   cluster
───┼─────────────────┼────────────┼────────────┼──────────────
 0 │ tenant_agent_00 │ staff      │ 0sec       │ prod-us-west
 1 │ tenant_agent_00 │ users      │ 0sec       │ prod-us-west
 2 │ tenant_agent_00 │ bookings   │ 0sec       │ prod-us-west
───┴─────────────────┴────────────┴────────────┴──────────────
```

```
> collections drop staff --scope tenant_agent_00
> collections --scope tenant_agent_00
───┬─────────────────┬────────────┬────────────┬──────────────
 # │      scope      │ collection │ max_expiry │   cluster
───┼─────────────────┼────────────┼────────────┼──────────────
 0 │ tenant_agent_00 │ users      │ 0sec       │ prod-us-west
 1 │ tenant_agent_00 │ bookings   │ 0sec       │ prod-us-west
───┴─────────────────┴────────────┴────────────┴──────────────
```

=== Listing `nodes`

The `nodes` command allows you to list all the nodes of the cluster you are currently connected to.

```
> nodes
───┬─────────┬─────────────────────┬─────────┬───────────────────┬───────────────────────┬──────────────────────────┬──────────────┬─────────────
 # │ cluster │ hostname            │ status  │ services          │ version               │ os                       │ memory_total │ memory_free 
───┼─────────┼─────────────────────┼─────────┼───────────────────┼───────────────────────┼──────────────────────────┼──────────────┼─────────────
 0 │ remote  │ 10.143.200.101:8091 │ healthy │ indexing,kv,query │ 6.5.0-4960-enterprise │ x86_64-unknown-linux-gnu │       2.1 GB │    837.7 MB 
 1 │ remote  │ 10.143.200.102:8091 │ healthy │ indexing,kv,query │ 6.5.0-4960-enterprise │ x86_64-unknown-linux-gnu │       2.1 GB │      1.0 GB 
───┴─────────┴─────────────────────┴─────────┴───────────────────┴───────────────────────┴──────────────────────────┴──────────────┴─────────────
```

=== Reading and Writing `doc`uments

The fastest way to interact with documents is through the key value service (as long as you know the document ID). All those commands are located as subcommands under the `doc` namespace.

==== Reading

You can retrieve a document with `doc get`:

```
> doc get airline_10
─────────┬─────────────────────
 id      │ airline_10
 cas     │ 1585811206390153216
 content │ [row 7 columns]
─────────┴─────────────────────
```

To distinguish the actual content from the metadata, the content is nested in the `content` field. If you want to have everything at the toplevel, you can pipe to the `flatten` command:

```
> doc get airline_10 | flatten
────────────┬─────────────────────
 id         │ airline_10
 cas        │ 1621356820428095488
 content_id │ 10
 type       │ airline
 name       │ 40-Mile Air
 iata       │ Q5
 icao       │ MLA
 callsign   │ MILE-AIR
 country    │ United States
 error      │
────────────┴─────────────────────
```

If the document is not found, an empty result is returned.

To perform a bulk get operation, the incoming stream can be utilized.

```
> echo [airline_10 airline_10748 airline_137] | wrap id | doc get
───┬───────────────┬─────────────────────┬─────────────────┬───────
 # │      id       │         cas         │     content     │ error
───┼───────────────┼─────────────────────┼─────────────────┼───────
 0 │ airline_10    │ 1621356820428095488 │ [row 7 columns] │
 1 │ airline_10748 │ 1621356818190237696 │ [row 7 columns] │
 2 │ airline_137   │ 1621356823346675712 │ [row 7 columns] │
───┴───────────────┴─────────────────────┴─────────────────┴───────
```

If `doc get` operates on an incoming stream it will extract the document id from the `id` column. This behavior can be customized through the `--id-column` flag.

==== Mutating

Documents can be mutated with `doc insert`, `doc upsert` and `doc replace`.

All those three commands take similar arguments. If you only want to mutate a single document, passing in the ID and the content as arguments is the simplest way:

```
> doc upsert my-doc {"hello": "world"}
───────────┬───
 processed │ 1 
 success   │ 1 
 failed    │ 0 
───────────┴───
```

Multiple documents can be mutated through an input stream as well, defaulting to the `id` and `content` columns:

==== Removing

Documents can be removed with `doc remove`.

```
> doc remove airline_10
───────────┬───
 processed │ 1 
 success   │ 1 
 failed    │ 0 
───────────┴───
```

Similar to `doc get`, if you want to delete more than one document at the same time, provide a stream of ids with an `id` column:

```
> echo [airline_10 airline_10748 airline_137] | wrap id | doc remove
───────────┬───
 processed │ 3 
 success   │ 2 
 failed    │ 1 
───────────┴───
```

=== `whoami`?

Sometimes simple commands are helpful when debugging. The `whoami` command will ask the same question to the active cluster and return various information about the user.

```
> whoami
─────────┬────────────────
 roles   │ [table 1 rows] 
 id      │ Administrator  
 domain  │ admin          
 cluster │ local          
─────────┴────────────────
```

Since a user can have many roles, if you want to look at them they need to be unnested:

```
> whoami | get roles
──────┬───────
 role │ admin 
──────┴───────
```

=== `version`

The `version` command lists the version of the couchbase shell.

```
> version
─────────┬───────────
 version │ 1.0.0-dev 
─────────┴───────────
```
