== Couchbase Commands

The following sections discuss the individual couchbase specific commands in greater detail. Remember, you can always mix and match them with built-in other shell commands as well as executables from your environment.

=== Working with `databases`

The `cb-env managed` command lists all the databases you have registered with the shell.

```
> cb-env managed
╭───┬────────┬───────┬────────────┬───────────────┬──────────────────────╮
│ # │ active │  tls  │ identifier │   username    │ capella_organization │
├───┼────────┼───────┼────────────┼───────────────┼──────────────────────┤
│ 0 │ true   │ false │ dev.local  │ Administrator │                      │
│ 1 │ false  │ true  │ capella    │ charlie       │                      │
╰───┴────────┴───────┴────────────┴───────────────┴──────────────────────╯
```

=== Working with `buckets`

The `buckets` command lists all the buckets from your active database:

```
> buckets
╭───┬───────────┬─────────────┬───────────┬──────────┬──────────────────────┬───────────┬───────────────┬────────┬───────╮
│ # │  cluster  │    name     │   type    │ replicas │ min_durability_level │ ram_quota │ flush_enabled │ status │ cloud │
├───┼───────────┼─────────────┼───────────┼──────────┼──────────────────────┼───────────┼───────────────┼────────┼───────┤
│ 0 │ dev.local │ beer-sample │ couchbase │        2 │ none                 │ 412.0 MiB │ false         │        │ false │
│ 1 │ dev.local │ default     │ couchbase │        0 │ none                 │ 512.0 MiB │ false         │        │ false │
│ 2 │ dev.local │ memd        │ memcached │        0 │ none                 │ 100.0 MiB │ false         │        │ false │
╰───┴───────────┴─────────────┴───────────┴──────────┴──────────────────────┴───────────┴───────────────┴────────┴───────╯
```

As an advanced command, it is also possible to get the configuration for a bucket:

```
> buckets config default
╭────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────╮
│ authType               │ sasl                                                                                 │
│ autoCompactionSettings │ false                                                                                │
│ basicStats             │ {record 8 fields}                                                                    │
│ bucketCapabilities     │ [list 17 items]                                                                      │
│ bucketCapabilitiesVer  │                                                                                      │
│ bucketType             │ membase                                                                              │
│ collectionsManifestUid │ 21                                                                                   │
│ compressionMode        │ passive                                                                              │
│ conflictResolutionType │ seqno                                                                                │
│ controllers            │ {record 4 fields}                                                                    │
│ ddocs                  │ {record 1 field}                                                                     │
│ durabilityMinLevel     │ none                                                                                 │
│ evictionPolicy         │ valueOnly                                                                            │
│ localRandomKeyUri      │ /pools/default/buckets/default/localRandomKey                                        │
│ maxTTL                 │ 0                                                                                    │
│ name                   │ default                                                                              │
│ nodeLocator            │ vbucket                                                                              │
│ nodes                  │ [table 1 row]                                                                        │
│ numVBuckets            │ 64                                                                                   │
│ pitrEnabled            │ false                                                                                │
│ pitrGranularity        │ 600                                                                                  │
│ pitrMaxHistoryAge      │ 86400                                                                                │
│ quota                  │ {record 2 fields}                                                                    │
│ replicaIndex           │ false                                                                                │
│ replicaNumber          │ 0                                                                                    │
│ stats                  │ {record 3 fields}                                                                    │
│ storageBackend         │ couchstore                                                                           │
│ streamingUri           │ /pools/default/bucketsStreaming/default?bucket_uuid=0ef162c33e14b163630f04639b347937 │
│ threadsNumber          │ 3                                                                                    │
│ uri                    │ /pools/default/buckets/default?bucket_uuid=0ef162c33e14b163630f04639b347937          │
│ uuid                   │ 0ef162c33e14b163630f04639b347937                                                     │
│ vBucketServerMap       │ {record 4 fields}                                                                    │
╰────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────╯
```

If you are unsure what you would use this for, you probably don't need it.

=== Working with `scopes` and `collections`

The `scopes` and `collections` commands can be used for managing scopes and collection respectively.

==== Scopes

```
> scopes -h
Fetches scopes through the HTTP API

Usage:
  > scopes <subcommand> {flags}

Subcommands:
  scopes create - Creates scopes through the HTTP API
  scopes drop - Deletes scopes through the HTTP API

Flags:
  -h, --help: Display this help message
  --bucket <string>: the name of the bucket
  --databases <string>: the databases to query against
```

To list all scopes in the bucket you would use:

```
> scopes
╭───┬─────────────────┬───────────╮
│ # │      scope      │  cluster  │
├───┼─────────────────┼───────────┤
│ 0 │ inventory       │ dev.local │
│ 1 │ tenant_agent_00 │ dev.local │
│ 2 │ tenant_agent_01 │ dev.local │
│ 3 │ tenant_agent_02 │ dev.local │
│ 4 │ tenant_agent_03 │ dev.local │
│ 5 │ tenant_agent_04 │ dev.local │
│ 6 │ _default        │ dev.local │
╰───┴─────────────────┴───────────╯
```

You can also create and remove scopes:

```
> scopes create tenant_agent_05
> scopes
╭───┬─────────────────┬───────────╮
│ # │      scope      │  cluster  │
├───┼─────────────────┼───────────┤
│ 0 │ tenant_agent_05 │ dev.local │
│ 1 │ inventory       │ dev.local │
│ 2 │ tenant_agent_00 │ dev.local │
│ 3 │ tenant_agent_01 │ dev.local │
│ 4 │ tenant_agent_02 │ dev.local │
│ 5 │ tenant_agent_03 │ dev.local │
│ 6 │ tenant_agent_04 │ dev.local │
│ 7 │ _default        │ dev.local │
╰───┴─────────────────┴───────────╯
```

```
> scopes drop tenant_agent_05
> scopes
╭───┬─────────────────┬───────────╮
│ # │      scope      │  cluster  │
├───┼─────────────────┼───────────┤
│ 0 │ inventory       │ dev.local │
│ 1 │ tenant_agent_00 │ dev.local │
│ 2 │ tenant_agent_01 │ dev.local │
│ 3 │ tenant_agent_02 │ dev.local │
│ 4 │ tenant_agent_03 │ dev.local │
│ 5 │ tenant_agent_04 │ dev.local │
│ 6 │ _default        │ dev.local │
╰───┴─────────────────┴───────────╯
```

==== Collections

```
> collections -h
Fetches collections through the HTTP API

Usage:
  > collections <subcommand> {flags}

Subcommands:
  collections create - Creates collections through the HTTP API
  collections drop - Deletes collections through the HTTP API

Flags:
  -h, --help: Display this help message
  --bucket <string>: the name of the bucket
  --scope <string>: the name of the scope
  --databases <string>: the databases to query against
```

To list all collection in the bucket you would use:

```
> collections
╭────┬─────────────────┬────────────┬────────────┬───────────╮
│  # │      scope      │ collection │ max_expiry │  cluster  │
├────┼─────────────────┼────────────┼────────────┼───────────┤
│  0 │ inventory       │ landmark   │       0sec │ dev.local │
│  1 │ inventory       │ hotel      │       0sec │ dev.local │
│  2 │ inventory       │ airport    │       0sec │ dev.local │
│  3 │ inventory       │ airline    │       0sec │ dev.local │
│  4 │ inventory       │ route      │       0sec │ dev.local │
│  5 │ tenant_agent_00 │ bookings   │       0sec │ dev.local │
│  6 │ tenant_agent_00 │ users      │       0sec │ dev.local │
│  7 │ tenant_agent_01 │ users      │       0sec │ dev.local │
│  8 │ tenant_agent_01 │ bookings   │       0sec │ dev.local │
│  9 │ tenant_agent_02 │ users      │       0sec │ dev.local │
│ 10 │ tenant_agent_02 │ bookings   │       0sec │ dev.local │
│ 11 │ tenant_agent_03 │ users      │       0sec │ dev.local │
│ 12 │ tenant_agent_03 │ bookings   │       0sec │ dev.local │
│ 13 │ tenant_agent_04 │ users      │       0sec │ dev.local │
│ 14 │ tenant_agent_04 │ bookings   │       0sec │ dev.local │
│ 15 │ _default        │ _default   │       0sec │ dev.local │
╰────┴─────────────────┴────────────┴────────────┴───────────╯
```

You can also create and remove collections:

```
> collections create staff --scope tenant_agent_00
> collections --scope tenant_agent_00
╭───┬─────────────────┬────────────┬────────────┬───────────╮
│ # │      scope      │ collection │ max_expiry │  cluster  │
├───┼─────────────────┼────────────┼────────────┼───────────┤
│ 0 │ tenant_agent_00 │ staff      │       0sec │ dev.local │
│ 1 │ tenant_agent_00 │ bookings   │       0sec │ dev.local │
│ 2 │ tenant_agent_00 │ users      │       0sec │ dev.local │
╰───┴─────────────────┴────────────┴────────────┴───────────╯
```

```
> collections drop staff --scope tenant_agent_00
> collections --scope tenant_agent_00
╭───┬─────────────────┬────────────┬────────────┬───────────╮
│ # │      scope      │ collection │ max_expiry │  cluster  │
├───┼─────────────────┼────────────┼────────────┼───────────┤
│ 0 │ tenant_agent_00 │ bookings   │       0sec │ dev.local │
│ 1 │ tenant_agent_00 │ users      │       0sec │ dev.local │
╰───┴─────────────────┴────────────┴────────────┴───────────╯
```

=== Listing `nodes`

The `nodes` command allows you to list all the nodes of the database you are currently connected to.

```
> nodes
───┬──────────┬─────────────────────┬─────────┬───────────────────┬───────────────────────┬──────────────────────────┬──────────────┬─────────────
 # │ database │ hostname            │ status  │ services          │ version               │ os                       │ memory_total │ memory_free 
───┼──────────┼─────────────────────┼─────────┼───────────────────┼───────────────────────┼──────────────────────────┼──────────────┼─────────────
 0 │ remote   │ 10.143.200.101:8091 │ healthy │ indexing,kv,query │ 6.5.0-4960-enterprise │ x86_64-unknown-linux-gnu │       2.1 GB │    837.7 MB 
 1 │ remote   │ 10.143.200.102:8091 │ healthy │ indexing,kv,query │ 6.5.0-4960-enterprise │ x86_64-unknown-linux-gnu │       2.1 GB │      1.0 GB 
───┴──────────┴─────────────────────┴─────────┴───────────────────┴───────────────────────┴──────────────────────────┴──────────────┴─────────────
```

=== Reading and Writing `doc`uments

The fastest way to interact with documents is through the key value service (as long as you know the document ID). 
All those commands are located as subcommands under the `doc` namespace.

==== Reading

You can retrieve a document with `doc get`:

```
> doc get airline_10
╭───┬────────────┬───────────────────┬─────────────────────┬───────┬───────────╮
│ # │     id     │      content      │         cas         │ error │  cluster  │
├───┼────────────┼───────────────────┼─────────────────────┼───────┼───────────┤
│ 0 │ airline_10 │ {record 7 fields} │ 1681456999724089344 │       │ dev.local │
╰───┴────────────┴───────────────────┴─────────────────────┴───────┴───────────╯
```

To distinguish the actual content from the metadata, the content is nested in the `content` field.
If you want to have everything at the toplevel, you can pipe to the `flatten` command:

```
> doc get airline_10 | flatten
╭───┬────────────┬──────────┬───────────────┬──────┬──────┬────────────┬─────────────┬─────────┬─────────────────────┬───────┬───────────╮
│ # │     id     │ callsign │    country    │ iata │ icao │ content_id │    name     │  type   │         cas         │ error │  cluster  │
├───┼────────────┼──────────┼───────────────┼──────┼──────┼────────────┼─────────────┼─────────┼─────────────────────┼───────┼───────────┤
│ 0 │ airline_10 │ MILE-AIR │ United States │ Q5   │ MLA  │         10 │ 40-Mile Air │ airline │ 1681456999724089344 │       │ dev.local │
╰───┴────────────┴──────────┴───────────────┴──────┴──────┴────────────┴─────────────┴─────────┴─────────────────────┴───────┴───────────╯
```

If the document is not found, an empty result is returned.

To perform a bulk get operation, the incoming stream can be utilized.

```
> echo [airline_10 airline_10748 airline_137] | wrap id | doc get
╭───┬───────────────┬───────────────────┬─────────────────────┬───────┬───────────╮
│ # │      id       │      content      │         cas         │ error │  cluster  │
├───┼───────────────┼───────────────────┼─────────────────────┼───────┼───────────┤
│ 0 │ airline_10    │ {record 7 fields} │ 1681456999724089344 │       │ dev.local │
│ 1 │ airline_10748 │ {record 7 fields} │ 1681456996753211392 │       │ dev.local │
│ 2 │ airline_137   │ {record 7 fields} │ 1681457004278579200 │       │ dev.local │
╰───┴───────────────┴───────────────────┴─────────────────────┴───────┴───────────╯
```

If `doc get` operates on an incoming stream it will extract the document id from the `id` column.
This behavior can be customized through the `--id-column` flag.

==== Mutating

Documents can be mutated with `doc insert`, `doc upsert` and `doc replace`.

All those three commands take similar arguments. If you only want to mutate a single document, passing in the ID and the content as arguments is the simplest way:

```
> doc upsert my-doc {"hello": "world"}
╭───┬───────────┬─────────┬────────┬──────────┬───────────╮
│ # │ processed │ success │ failed │ failures │  cluster  │
├───┼───────────┼─────────┼────────┼──────────┼───────────┤
│ 0 │         1 │       1 │      0 │          │ dev.local │
╰───┴───────────┴─────────┴────────┴──────────┴───────────╯
```

Multiple documents can be mutated through an input stream as well, defaulting to the `id` and `content` columns:

==== Removing

Documents can be removed with `doc remove`.

```
> doc remove airline_10
╭───┬───────────┬─────────┬────────┬──────────┬───────────╮
│ # │ processed │ success │ failed │ failures │  cluster  │
├───┼───────────┼─────────┼────────┼──────────┼───────────┤
│ 0 │         1 │       1 │      0 │          │ dev.local │
╰───┴───────────┴─────────┴────────┴──────────┴───────────╯
```

Similar to `doc get`, if you want to delete more than one document at the same time, provide a stream of ids with an `id` column:

```
> echo [airline_10 airline_10748 airline_137] | wrap id | doc remove
╭───┬───────────┬─────────┬────────┬───────────────┬───────────╮
│ # │ processed │ success │ failed │   failures    │  cluster  │
├───┼───────────┼─────────┼────────┼───────────────┼───────────┤
│ 0 │         3 │       2 │      1 │ Key not found │ dev.local │
╰───┴───────────┴─────────┴────────┴───────────────┴───────────╯
```

=== `version`

The `version` command lists the version of the couchbase shell.

```
> version
╭─────────┬────────╮
│ version │ 0.75.1 │
╰─────────┴────────╯
```
