== Couchbase Commands

The following sections discuss the individual couchbase specific commands in greater detail. Remember, you can always mix and match them with built-in other shell commands as well as executables from your environment.

=== Preface: the `--clusters` flag

On many commands, you will notice a flag called `--clusters`. This flag allows you to run the specific command not just against the active cluster, but rather against a group of clusters that the shell knows about. The argument for this flag is an identifier combined with a regular expression. So imagine you have three clusters setup with the following identifiers:

```
> clusters | get identifier
───┬────────
 0 │ prod-us-west
 1 │ prod-us-east
 2 │ prod-eu-center
 3 │ local-test
───┴────────
```

If you wanted to run a command against all clusters in `prod-us`, you could use `--clusters prod-us.*`. In the background this gets passed to a regex engine, so you can go a little crazy with it if needed.


=== `use` and the Environment

While mulitple clusters can be connected at the same time, there is only ever one cluster (at most) active. The same is true for a bucket inside that cluster.

You can run the `use` command, which will tell you which cluster and bucket are currently active (you are also able to tell from the prompt):

```
> use
─────────┬───────────────
 cluster │ local         
 bucket  │ travel-sample 
─────────┴───────────────
```

Changing the active cluster is done via `use cluster`, and changing the active bucket via `use bucket`:

```
> use bucket beer-sample
────────┬─────────────
 bucket │ beer-sample 
────────┴─────────────
```

```
> use
─────────┬─────────────
 cluster │ local       
 bucket  │ beer-sample 
─────────┴─────────────
```

Both the output of `use` and the prompt will reflect the changes.

=== Working with `clusters`

The `clusters` command lists all the clusters you specified in your configuration and the shell might be connected to.

```
> clusters
───┬────────┬─────┬────────────┬───────────────
 # │ active │ tls │ identifier │ username      
───┼────────┼─────┼────────────┼───────────────
 0 │ No     │ No  │ local      │ Administrator 
 1 │ Yes    │ No  │ remote     │ Administrator
───┴────────┴─────┴────────────┴───────────────
```

=== Working with `buckets`

The `buckets` command lists all the buckets from your active cluster:

```
> buckets
───┬─────────┬─────────────────────┬─────────
 # │ cluster │ name                │ type    
───┼─────────┼─────────────────────┼─────────
 0 │ local   │ beer-sample         │ membase 
 1 │ local   │ default             │ membase 
 3 │ local   │ travel-sample       │ membase 
───┴─────────┴─────────────────────┴─────────
```

As an advanced command, it is also possible to get the configuration for a bucket:

```
> buckets config beer-sample
────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────
 name                   │ beer-sample                                                                              
 uuid                   │ 0af4496fe0612c76885d5dcd3e010c0d                                                         
 bucketType             │ membase                                                                                  
 authType               │ sasl                                                                                     
 uri                    │ /pools/default/buckets/beer-sample?bucket_uuid=0af4496fe0612c76885d5dcd3e010c0d          
 streamingUri           │ /pools/default/bucketsStreaming/beer-sample?bucket_uuid=0af4496fe0612c76885d5dcd3e010c0d 
 localRandomKeyUri      │ /pools/default/buckets/beer-sample/localRandomKey                                        
 controllers            │ [row compactAll compactDB purgeDeletes startRecovery]                                    
 nodes                  │ [table 1 rows]                                                                           
 stats                  │ [row directoryURI nodeStatsListURI uri]                                                  
 nodeLocator            │ vbucket                                                                                  
 saslPassword           │ 7fd7338a6b8fb30dbfb80205834db634                                                         
 ddocs                  │ [row uri]                                                                                
 replicaIndex           │ Yes                                                                                      
 autoCompactionSettings │ No                                                                                       
 vBucketServerMap       │ [row hashAlgorithm numReplicas serverList vBucketMap]                                    
 maxTTL                 │ 0                                                                                        
 compressionMode        │ passive                                                                                  
 replicaNumber          │ 1                                                                                        
 threadsNumber          │ 3                                                                                        
 quota                  │ [row ram rawRAM]                                                                         
 basicStats             │ [row 8 columns]                                                                          
 evictionPolicy         │ valueOnly                                                                                
 conflictResolutionType │ seqno                                                                                    
 bucketCapabilitiesVer  │                                                                                          
 bucketCapabilities     │ [table 9 rows]                                                                           
────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────
```

If you are unsure what you would use this for, you probably don't need it.

=== Listing `nodes`

The `nodes` command allows you to list all the nodes of the cluster you are currently connected to.

```
> nodes
───┬─────────┬─────────────────────┬─────────┬───────────────────┬───────────────────────┬──────────────────────────┬──────────────┬─────────────
 # │ cluster │ hostname            │ status  │ services          │ version               │ os                       │ memory_total │ memory_free 
───┼─────────┼─────────────────────┼─────────┼───────────────────┼───────────────────────┼──────────────────────────┼──────────────┼─────────────
 0 │ remote  │ 10.143.200.101:8091 │ healthy │ indexing,kv,query │ 6.5.0-4960-enterprise │ x86_64-unknown-linux-gnu │       2.1 GB │    837.7 MB 
 1 │ remote  │ 10.143.200.102:8091 │ healthy │ indexing,kv,query │ 6.5.0-4960-enterprise │ x86_64-unknown-linux-gnu │       2.1 GB │      1.0 GB 
───┴─────────┴─────────────────────┴─────────┴───────────────────┴───────────────────────┴──────────────────────────┴──────────────┴─────────────
```

=== Reading and Writing `doc`uments

The fastest way to interact with documents is through the key value service (as long as you know the document ID). All those commands are located as subcommands under the `doc` namespace.

You can retrieve a document with `doc get`:

```
> doc get airline_10
─────────┬─────────────────────
 id      │ airline_10
 cas     │ 1585811206390153216
 content │ [row 7 columns]
─────────┴─────────────────────
```

To distinguish the actual content from the metadata, the content is nested in the `content` field. If you want to have everything at the toplevel, you can use the `--flatten` flag:

```
> doc get airline_10 --flatten
──────────┬─────────────────────
 id       │ 10                  
 cas      │ 1585811206390153216 
 country  │ United States       
 iata     │ Q5                  
 callsign │ MILE-AIR            
 name     │ 40-Mile Air         
 icao     │ MLA                 
 type     │ airline             
──────────┴─────────────────────
```

If the document is not found, an empty result is returned.

To perform a bulk get operation, the incoming stream can be utilized.

```
> echo [airline_10 airline_10748 airline_137] | wrap id | doc get
───┬───────────────┬─────────────────────┬─────────────────
 # │ id            │ cas                 │ content         
───┼───────────────┼─────────────────────┼─────────────────
 0 │ airline_10    │ 1594902508775604224 │ [row 7 columns] 
 1 │ airline_10748 │ 1594902508776521728 │ [row 7 columns] 
 2 │ airline_137   │ 1594902508777439232 │ [row 7 columns] 
───┴───────────────┴─────────────────────┴─────────────────
```

If `doc get` operates on an incoming stream it will extract the document id from the `id` column. This behavior can be customized through the `--id-column` flag.

=== Interacting with the `data` service

Note that the `data` commands are intended to work directly against the data (Key/Value) service. If you are looking for manipulating doucments, please use the `doc` commands instead.

You can use the `data stats` subcommand to list the KV stats for all the nodes connected for the current cluster. In the following example we are filtering on a subset of the stats since the full output can get quite verbose.

```
> data stats | where key =~ cmd_
────┬─────────┬───────────┬──────────────────────────────┬──────────
 #  │ cluster │ node      │ key                          │ value    
────┼─────────┼───────────┼──────────────────────────────┼──────────
 0  │ local   │ 127.0.0.1 │ cmd_get                      │ 2095     
 1  │ local   │ 127.0.0.1 │ cmd_set                      │ 1        
 2  │ local   │ 127.0.0.1 │ cmd_flush                    │ 0        
 3  │ local   │ 127.0.0.1 │ cmd_subdoc_lookup            │ 0        
 4  │ local   │ 127.0.0.1 │ cmd_subdoc_mutation          │ 0        
 5  │ local   │ 127.0.0.1 │ cmd_total_sets               │ 41049    
 6  │ local   │ 127.0.0.1 │ cmd_total_gets               │ 12595    
 7  │ local   │ 127.0.0.1 │ cmd_total_ops                │ 53644    
 8  │ local   │ 127.0.0.1 │ cmd_mutation                 │ 2        
 9  │ local   │ 127.0.0.1 │ cmd_lookup                   │ 2095     
 10 │ local   │ 127.0.0.1 │ cmd_lock                     │ 0        
 11 │ local   │ 127.0.0.1 │ cmd_lookup_10s_count         │ 0        
 12 │ local   │ 127.0.0.1 │ cmd_lookup_10s_duration_us   │ 0        
 13 │ local   │ 127.0.0.1 │ cmd_mutation_10s_count       │ 536440   
 14 │ local   │ 127.0.0.1 │ cmd_mutation_10s_duration_us │ 22059071 
────┴─────────┴───────────┴──────────────────────────────┴──────────
```

=== `whoami`?

Sometimes simple commands are helpful when debugging. The `whoami` command will ask the same question to the active cluster and return various information about the user.

```
> whoami
─────────┬────────────────
 roles   │ [table 1 rows] 
 id      │ Administrator  
 domain  │ admin          
 cluster │ local          
─────────┴────────────────
```

Since a user can have many roles, if you want to look at them they need to be unnested:

```
> whoami | get roles
──────┬───────
 role │ admin 
──────┴───────
```

=== `version`

The `version` command lists the version of the couchbase shell.

```
> version
─────────┬───────────
 version │ 1.0.0-dev 
─────────┴───────────
```