== Introduction

Couchbase Shell is fully featured, so it does not only contain commands related to couchbase but is actually built on top of a general purpose shell called https://www.nushell.sh/[nushell]. This allows you to interact with the file system or any other command available on your machine, making it a great tool for both operational and development tasks on top of Couchbase.

The following introduction only touches on the basic concepts to make you productive quickly. We recommend also checking out the great https://www.nushell.sh/book[nushell documentation] so you can get the most out of it.

=== Navigating the Shell

Commands take inputs and produce output in a structured manner, most often represented as tables. Note how both the generic `ls` command and the couchbase-specific `buckets` command both produce a table as their output:

```
> ls
â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
 #  â”‚     name     â”‚ type â”‚   size   â”‚    modified
â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  0 â”‚ CHANGELOG.md â”‚ File â”‚   4.8 KB â”‚ 2 hours ago
  1 â”‚ Cargo.lock   â”‚ File â”‚ 170.2 KB â”‚ 16 minutes ago
  2 â”‚ Cargo.toml   â”‚ File â”‚   1.8 KB â”‚ 16 minutes ago
  3 â”‚ LICENSE      â”‚ File â”‚  11.4 KB â”‚ 2 days ago
  4 â”‚ README.md    â”‚ File â”‚   8.6 KB â”‚ 9 minutes ago
  5 â”‚ docs         â”‚ Dir  â”‚    544 B â”‚ 2 days ago
  6 â”‚ examples     â”‚ Dir  â”‚    192 B â”‚ 2 days ago
  7 â”‚ jupyter      â”‚ Dir  â”‚    128 B â”‚ 2 days ago
  8 â”‚ src          â”‚ Dir  â”‚    256 B â”‚ 2 days ago
  9 â”‚ target       â”‚ Dir  â”‚    224 B â”‚ 32 minutes ago
 10 â”‚ tests        â”‚ Dir  â”‚    224 B â”‚ 2 days ago
â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
```

```
> buckets
â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€
 # â”‚ cluster  â”‚     name      â”‚   type    â”‚ replicas â”‚ min_durability_level â”‚ ram_quota â”‚ flush_enabled â”‚ status â”‚ cloud
â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€
 0 â”‚ default  â”‚ beer-sample   â”‚ couchbase â”‚        1 â”‚ none                 â”‚  209.7 MB â”‚ false         â”‚        â”‚ false
 1 â”‚ default  â”‚ default       â”‚ couchbase â”‚        1 â”‚ none                 â”‚  104.9 MB â”‚ true          â”‚        â”‚ false
 2 â”‚ default  â”‚ targetBucket  â”‚ couchbase â”‚        0 â”‚ none                 â”‚  104.9 MB â”‚ true          â”‚        â”‚ false
 3 â”‚ default  â”‚ travel-sample â”‚ couchbase â”‚        1 â”‚ none                 â”‚  209.7 MB â”‚ false         â”‚        â”‚ false
â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€
```

You can pipe the output into other commands, for example if you only want to see buckets that have `sample` in their name you can utilize the `where` command:

```
> buckets | where name =~ "sample"
â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€
 # â”‚ cluster  â”‚     name      â”‚   type    â”‚ replicas â”‚ min_durability_level â”‚ ram_quota â”‚ flush_enabled â”‚ status â”‚ cloud
â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€
 0 â”‚ default  â”‚ beer-sample   â”‚ couchbase â”‚        1 â”‚ none                 â”‚  209.7 MB â”‚ false         â”‚        â”‚ false
 1 â”‚ default  â”‚ travel-sample â”‚ couchbase â”‚        1 â”‚ none                 â”‚  209.7 MB â”‚ false         â”‚        â”‚ false
â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€
```

In a similar fashion you can turn this structured table into other output formats, for example JSON:

```
> buckets | where name =~ "sample" | to json --pretty 2
[
  {
    "cluster": "default",
    "name": "beer-sample",
    "type": "couchbase",
    "replicas": 1,
    "min_durability_level": "none",
    "ram_quota": 209715200,
    "flush_enabled": false,
    "status": "",
    "cloud": false
  },
  {
    "cluster": "default",
    "name": "travel-sample",
    "type": "couchbase",
    "replicas": 1,
    "min_durability_level": "none",
    "ram_quota": 209715200,
    "flush_enabled": false,
    "status": "",
    "cloud": false
  }
]
```

Exactly this type of composition takes the unix philosophy of "do one thing well" and meshes it together with the idea of flexible structured pipelines. This allows to build powerful compositions that help you in your daily operations with Couchbase, both from a developer or operations point of view.

=== Getting Help

Other than using this documentation for help, each command can be called with `-h` or `--help` to get information about potential flags, arguments and subcommands. Also, some commands provide additional examples.

```
> buckets -h
Perform bucket management operations

Usage:
  > buckets <subcommand> {flags}

Subcommands:
  buckets config - Shows the bucket config (low level)
  buckets create - Creates a bucket
  buckets drop - Drops buckets through the HTTP API
  buckets flush - Flushes buckets through the HTTP API
  buckets get - Fetches buckets through the HTTP API
  buckets load-sample - Load a sample bucket
  buckets update - Updates a bucket

Flags:
  -h, --help: Display this help message
  --clusters <string>: the clusters which should be contacted
```

Some commands (like the one above) only act as groupings for subcommands, like `from`, `to` or `doc`. Since they do not serve a purpose on their own, they will render their help output automatically:

```
> doc
Perform document operations against a bucket or collection

Usage:
  > doc <subcommand> {flags}

Subcommands:
  doc get - Fetches a document through the data service
  doc insert - Insert a document through the data service
  doc remove - Removes a document through the data service
  doc replace - Replace a document through the data service
  doc upsert - Upsert (insert or override) a document through the data service

Flags:
  -h, --help: Display this help message
```

=== The Prompt explained
Couchbase Shell uses a custom, two line prompt to show you exactly in what environment you are working in right now. Since you can connect to different clusters, switch buckets etc. it is important to know what is currently "active". Here is a sample prompt that will greet you when starting the shell:

```
ðŸ‘¤ Administrator at ðŸ  local in ðŸ—„ travel-sample
>
```

It tells you that your user is `Administrator`, the current active cluster identifier is `local` and the active bucket is `travel-sample`.

If you have an active scope or collection set then the prompt will also update to reflect that:

```
ðŸ‘¤ Administrator ðŸ  dev.local in ðŸ—„ travel-sample.myscope.mycollection
>
```

In the second line, your actual user prompt starts.

=== Loading Data into the Shell

If you want to import data into Couchbase, or just load it into the shell for further processing, there are different commands available to help you.
Once the data is loaded into the shell it can be sent to one of the couchbase save commands like `doc upsert` and `doc import`.
Depending on the structure of the data, and the command used, you may also need to tweak it a little bit so it can be properly stored.

==== Doc import

The `doc import` is the simplest way to import data through Couchbase Shell.
The command expects a path to file containing data, the data can be any of the formats supported by the `from` command.
In the following example we import a json file containing a single document.
We also specify the `--id-column` flag because `doc import` will try to use an `id` field for the document key by default.

```
> cat user.json
{
  "name": "Michael",
  "age": 32,
  "height": 180
}

> doc import user.json --id-column name
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ processed â”‚ success â”‚ failed â”‚ failures â”‚  cluster  â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚         1 â”‚       1 â”‚      0 â”‚          â”‚ dev.local â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

```
> doc import -h
Import documents from a file through the data service

Usage:
  > doc import {flags} <filename>

Flags:
  -h, --help - Display the help message for this command
  --id-column <String> - the name of the id column if used with an input stream
  --bucket <String> - the name of the bucket
  --expiry <Number> - the expiry for the documents in seconds, or absolute
  --scope <String> - the name of the scope
  --collection <String> - the name of the collection
  --clusters <String> - the clusters which should be contacted
  --batch-size <Number> - the maximum number of items to batch send at a time

Parameters:
  filename <string>: the path to the file containing data to import
```

==== Manual import

The `open` command will look at file endings and try to decode it automatically.
Imagine a file named `user.json` in your current directory.

```
> cat user.json
{
  "name": "Michael",
  "age": 32,
  "height": 180
}

> open user.json
â•­â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ name   â”‚ Michael â”‚
â”‚ age    â”‚ 32      â”‚
â”‚ height â”‚ 180     â”‚
â•°â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

As you can see, the `open` command automatically decoded the JSON document into the tabular format.
If the filename would only be `user`, the import would look like this instead:

```
> open user
{
  "name": "Michael",
  "age": 32,
  "height": 180
}
```

If you are dealing with data that cannot be decoded automatically, you can use the various `from` subcommands to help with decoding.
In our case we use `from json`:

```
> open user | from json
â•­â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ name   â”‚ Michael â”‚
â”‚ age    â”‚ 32      â”‚
â”‚ height â”‚ 180     â”‚
â•°â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

TIP: look at the many different import formats `from` supports, including csv, xml, yaml and even sqlite. With this simple tool at hand you are able to load many different data formats quickly and import them into couchbase!

We cannot use this format directly with commands like `doc upsert` as the command expects two "columns" in the data - id and content.
This means that we have to perform some translation from the above format to one that `doc upsert` understands.
To do this we `wrap` the entire document into a content column and then extract the id that we want to use:

```
> open user.json | wrap content | insert id {|it| echo $it.content.name}
â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ content â”‚ {record 3 fields} â”‚
â”‚ id      â”‚ Michael           â”‚
â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

There are many other approaches to achieving this same result.
With our data in the correct format we can then upsert:

```
> open user.json | wrap content | insert id {|it| echo $it.content.name} | doc upsert
â•­â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ # â”‚ processed â”‚ success â”‚ failed â”‚ failures â”‚  cluster  â”‚
â”œâ”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤
â”‚ 0 â”‚         1 â”‚       1 â”‚      0 â”‚          â”‚ dev.local â”‚
â•°â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
```

See the xref:recipes/importing-data.adoc[Importing data recipes] for more information.

=== Exporting Data from the Shell

The export counterparts to `open` and `from`, are `save` and `to`.
You can use both commands to take tabular data from the shell and store it in files of the needed target format.

Like `open`, `save` will try to discern the format from the file ending.
The following example will load a JSON file and then save it as CSV:

```
> cat user.json
{
  "name": "Michael",
  "age": 32,
  "height": 180
}
```

```
> open user.json | save user.csv
```

```
> cat user.csv
name,age,height
Michael,32,180
```

This example is dealing with only one row for simplicity, but you can save as many rows as you need in one file.

As a motivating example, the following snippet runs a N1QL query and stores the result as a csv file:

```
> query "select airportname,city,country from `travel-sample` where type = 'airport' limit 10" | save output.csv
```

```
> cat output.csv
airportname,city,country
Calais Dunkerque,Calais,France
Peronne St Quentin,Peronne,France
Les Loges,Nangis,France
Couterne,Bagnole-de-l'orne,France
Bray,Albert,France
Le Touquet Paris Plage,Le Tourquet,France
Denain,Valenciennes,France
Glisy,Amiens,France
La Garenne,Agen,France
Cazaux,Cazaux,France
```

See the xref:recipes/exporting-data.adoc[Exporting data recipes] for more information.
